### ISSUE TITLE
Monterey 12.1 update not visible after update to OCLP 0.3.2

### ISSUE THREAD

**Issue by walterbressers** [dortania/OpenCore-Legacy-Patcher#800] opened 2021-12-14 08:34 UTC
### Machine Model

iMac13,1

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Issue?

I verified on 2 machines. After installing OCLP release 0.3.2 OS Monterey update 12.1 was not visible in the Software update panel. Before installing 0.3.2 it was visible. Probably something to do with the new spoofless support? I can try a complete new install?

**Comment by iFloris** [comment] 2021-12-14 08:50
Same on my MacPro3,1

**Comment by ElreboCM** [comment] 2021-12-14 10:02
This is a duplicate of #798. 
I

**Comment by walterbressers** [comment] 2021-12-14 10:14
I didn't see #798

**Closed** 2021-12-14 10:14 UTC
Labels: bug
