### ISSUE TITLE
Support for models with dead non-removable internal SSD

### ISSUE THREAD

**Issue by stepin** [dortania/OpenCore-Legacy-Patcher#878] opened 2022-01-09 14:09 UTC
It's more a feature request than a bug.

Apple started to produce models with non-removeable internal SSD years ago. If SSD becomes dead it's really expensive to replace it (full motherboard replacement officially or expensive long replacement of SSD unofficially). If internal SSD is dead it's impossible to install operating system without hackintosh-like activities. So, for me looks like OpenCore Legacy Patcher can be used in this case as this project brings second life for Apple machines.

I tried to do it myself for a week but failed. I think that best scenario is to hide old internal ssd and to make external usb ssd look like internal drive. In this case even firmware upgrades can be done (at least in my idea).

Maybe even development is not needed and it's documentation-only issue. Or at least partial solution without firmware upgrade (it will allow to install previously installed version (Catalina in my case) but not latest OS as I understand).

Some details for my case:

I have a MacBookPro13,3. I tried to hide internal SSD using:
```
	<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1B,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>device-id</key>
				<data>/////w==</data>
				<key>device_type</key>
				<string>Internal dead SSD</string>
				<key>vendor-id</key>
				<data>/////w==</data>
			</dict>
		</dict>
		<key>Delete</key>
		<dict/>
	</dict>
```

External SSD info (from Linux's `lsusb`):
```
Bus 004 Device 002: ID 04e8:4001 Samsung Electronics Co., Ltd PSSD T7
```
and from macos (initially I was able to install original version of macos 10.12 but even this I can't repeat now):
```
$ ioreg -p IOUSB
+-o Root  <class IORegistryEntry, id 0x100000100, retain 28>
  +-o Root Hub Simulation Simulation@14000000  <class AppleUSBRootHubDevice, id 0x1000003dc, registered, matched, active, busy 0 (11 ms), retain 12>
  | +-o iBridge@14200000  <class AppleUSBDevice, id 0x1000013a3, registered, matched, active, busy 0 (315 ms), retain 35>
  +-o Root Hub Simulation Simulation@00000000  <class AppleUSBRootHubDevice, id 0x100000400, registered, matched, active, busy 0 (11 ms), retain 9>
    +-o PSSD T7@00200000  <class AppleUSBDevice, id 0x100000402, registered, matched, active, busy 0 (12 ms), retain 14>
    
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB2@2/IOPP/XHC2@0/XHC2@00000000/SSP2@00200000
PCI0.PEG1.UPSB.DSB2.XHC2.XHC2.SSP2
```

**Comment by khronokernel** [comment] 2022-01-09 16:39
Hello, unfortunately what you're hoping to achieve is not possible as you have laid out.

> I think that best scenario is to hide old internal ssd and to make external usb ssd look like internal drive. In this case even firmware upgrades can be done (at least in my idea).

Firmware updates are based off the stock system configurations with different drivers applying updated from `efiupdater`. One of the curial factors to ensure firmware updates succeed is to have the same protocol drive as what your system shipped with. Unless you're able to solder a PCIe M.2 slot onto the board, Thunderbolt and USB based solutions will not be supported as firmware update mediums.

> I have a MacBookPro13,3. I tried to hide internal SSD using:

Regarding this, the only important property you need is to set a botched `class-code` as that's all IONVMeFamily uses for determining whether to attach or not. 

--------

With regards to resolving your installation issue, the most applicable solution would be to apply VMM masking to your system as we do with unsupported machines in newer OSes. This allows you to negate the reliance on firmware versioning as macOS has explicit exemptions for VMM. This system is supported with macOS Big Sur and newer (11.3+).

The other concern that remains is the internal drive situation. To better determine how to proceed, could you answer a couple questions:

1. How is the SSD "dead"? Is the drive controller broken, locked in read-only mode, certain NAND dead, etc
2. How does macOS react with this dead SSD by default? Does IONVMeFamily kernel panic, OS become unstable, etc

**Comment by stepin** [comment] 2022-01-09 18:59
Thanks for the fast answer and clarification about efiupdater. At least it's clear now that it should be installed like hackintosh.

About internal disk: system boot is in progress (after login/password screen) and then it reboots to black screen with blinking folder with a question mark on it and "support.apple.com/mac/startup" (screens attached, looks like it's https://support.apple.com/HT204323 ). Disk is encrypted. In general, I don't need data from it. Disk is not visible in the Disk Utility and in the Linux's `lsblk` but it's visible in the Linux's `lspci`.

![IMG_9722](https://user-images.githubusercontent.com/25543/148696493-4abaaa92-a56f-456e-a350-3b9c456716da.PNG)

![IMG_9723](https://user-images.githubusercontent.com/25543/148696521-aa132d97-88ff-43a2-b852-4e47894540d7.PNG)

**Comment by khronokernel** [comment] 2022-01-15 01:20
With the latest commit I've added the option to spoof native models (see SMBIOS settings after toggling "Allow native models"):

* https://github.com/dortania/OpenCore-Legacy-Patcher/suites/4944956421/artifacts/143281890
  * Need to be signed into Github to download (ie. if you're viewing from an email, etc)

However this only implements a portion of what was requested, as disabling the SSD was not implemented yet. 

Additionally I have only just realized that this machine might not be able to run OCLP to do the hardware probe. Thus my question is, do you have a build of macOS you *can* boot? More specifically do you have an installation of Sierra (or any other macOS install really) that's on an external drive that you can use?

If so, then testing the above commit shouldn't be an issue (our builds support 10.10+). Would like to validate that the commit works as intended, and whether disabling the SSD is still required.

* Our current system for detecting PCIe devices would actually be masked if we disable them, so would need to put some extra engineering into that. If needed, no issue implementing however would like to verify first

**Comment by stepin** [comment] 2022-01-16 22:47
Currently, I have only Linux on it. I will try to install macOS on it like on pc to test this build.

**Comment by khronokernel** [comment] 2022-02-05 16:32
Due to the time elapsed, going to close this issue assuming this resolved the installation issues. Feel free to comment in the future and we can reopen the issue

**Closed by khronokernel** 2022-02-05 16:32 UTC
Labels: enhancement, back-end
