### ISSUE TITLE
[Bug]: MBP5,2 booting stalls after having applied the volume patches

### ISSUE THREAD

**Issue by hvdschmitt** [dortania/OpenCore-Legacy-Patcher#584] opened 2021-10-17 21:40 UTC
### Machine Model

MacBookPro5,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Between booting macOS and Login Screen

### What is the Isssue?

Installation of 12.0b10 with 0.3.0 TUI works fine right to user login and works well, repeated booting also ok.
After applying the volume patch however, booting stalls (progress bar hangs, external SSD which I use for Monterey shows no activity anymore).

Photo taken with 0.3.0 in verbose, at the point where boot stalls, is attached. Also attached is the log shown when booting into Big Sur after that. This log looks the same as RogueB's in his report #580.

Same behaviour already observed with beta9 and 0.3.0 nightly from 12Oct (but didn't follow up - sorry)

![IMG_6234](https://user-images.githubusercontent.com/82234458/137645886-30f3ccb1-a363-4da0-bb2d-6fe5fbf26ab7.JPG)

[KP-b10-030.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7360909/KP-b10-030.txt)

**Comment by khronokernel** [comment] 2021-10-17 21:47
Likely a duplicate of this:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/580

Will revert [this patch set](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/514) to avoid further issues

**Closed** 2021-10-17 21:53 UTC
Labels: bug

**Comment by hvdschmitt** [comment] 2021-10-18 10:47
Thank you, really AppleMuxControl.kext was the culprit. Reverting it to the stock beta10 version made my installation bootable, and it runs very well on my MBP5,2.
Will use 0.3.1 next time.

------
Hans von der Schmitt
***@***.***
