### ISSUE TITLE
[Bug]: iMac11,3 (GTX 880m) incompatibilities with BacklightInjector

### ISSUE THREAD

**Issue by kwnage** [dortania/OpenCore-Legacy-Patcher#538] opened 2021-10-04 16:30 UTC
### Machine Model

iMac11,3

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

Backlight control doesn't work at all on Big Sur Version 11.6 when BacklightInjector.kext is enabled. Disabling it will restore backlight control albeit without full brightness. Adding AppleBacklightFixup.kext doesn't help, neither with BacklightInjector.kext enabled nor with it disabled.

On High Sierra backlight control with full brightness works after adding AppleBacklightFixup.kext.

Same thing with latest nightly build.

Going back to 0.2.4, backlight control still does not work with BacklightInjector.kext enabled. Disabling it and adding AppleBacklightFixup.kext will restore backlight control with full brightness.

### Any Additional Information

I'm using a flashed GTX 880m

**Comment by grzegorz914** [comment] 2021-10-04 16:33
Same for Monterey beta 8 on iMac 11,3 with Nvidia, also no acceleration

**Comment by kwnage** [comment] 2021-10-04 16:38
> @kwnage Upload generated 0.2.4 and 0.2.5 OpenCore-Build folders
Just the bare folders that TUI generated or do you need the modifications I did to it for full brightness as well?

**Comment by khronokernel** [comment] 2021-10-04 16:47
@kwnage 
> Going back to 0.2.4, backlight control still does not work with BacklightInjector.kext enabled. Disabling it and adding AppleBacklightFixup.kext will restore backlight control with full brightness.

AppleBacklightFixup.kext is a very dead kext, WhateverGreen superseded it with the `applbkl` property. Need to ensure this is correctly injected

**Comment by grzegorz914** [comment] 2021-10-04 16:53
@khronokernel  
acceleration and backlight was working fine before beta 7

**Comment by khronokernel** [comment] 2021-10-04 16:54
> acceleration and backlight was working fine before beta 7
Well ofc, Apple killed Kepler in Beta 7

**Comment by kwnage** [comment] 2021-10-04 17:28
@khronokernel 
[OpenCore-Build_0.2.5.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7279998/OpenCore-Build_0.2.5.zip)
[OpenCore-Build_0.2.4.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7280004/OpenCore-Build_0.2.4.zip)

These are fresh builds. I tried both of them again to ensure the issue is still the same.

> AppleBacklightFixup.kext is a very dead kext, WhateverGreen superseded it with the applbkl property. Need to ensure this is correctly injected. So yes, unmodified folders

Yeah I noticed AppleBacklightFixup.kext is quite old. However, I did not know that WhateverGreen was supposed to take over its role. Thank you for the clarification. :)

**Comment by khronokernel** [comment] 2021-10-04 17:40
So I found the reason why back porting AppleBacklightFixup.kext only works on 0.2.4, we had the boot-arg `-lilubetaall` installed which removes the OS check from Lilu and plugins. AppleBacklightFixup.kext was never compiled for newer OSes.

With regards to why WEG doesn't want to work, I can see both builds inject the property correctly:
```xml
			<key>PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>@0,backlight-control</key>
				<data>
				AQAAAA==
				</data>
				<key>@0,built-in</key>
				<data>
				AQAAAA==
				</data>
				<key>agdpmod</key>
				<string>vit9696</string>
				<key>applbkl</key>
				<data>
				AQAAAA==
				</data>
				<key>shikigva</key>
				<integer>256</integer>
			</dict>
```
And with this comment:
> Backlight control doesn't work at all on Big Sur Version 11.6 when BacklightInjector.kext is enabled. Disabling it will restore backlight control albeit without full brightness.

This hints to a panel mismatch issue within our injector. Can you upload the AppleBacklightFixup.kext you are using for these tests?

**Comment by kwnage** [comment] 2021-10-04 17:42
Sure.

[AppleBacklightFixup.kext.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7280121/AppleBacklightFixup.kext.zip)

**Comment by khronokernel** [comment] 2021-10-04 17:46
@Ausdauersportler Would it be possible for you to take a peak at this? Unfortunately not too familiar with iMac Graphics mods, as you were the one who provided the original patch sets.

Source for our current injector:

* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/payloads/Kexts/Misc/BacklightInjector-v1.0.0.zip

**Comment by Ausdauersportler** [comment] 2021-10-05 07:57
Hello!

Unfortunately without having an Nvidia based machine I am as blind as your are. 

The current BacklightInjector (as linked in) has already one entry **more** than the older version of AppleBacklightFixup uploaded here. So I am not sure if a missing entry can be the cause of the problem.

@kwnage Could you please provide your panel type using this procedure:

Your panel ID can be found by going to System Preferences > Displays > Color > Open Profile > mmod

**Comment by kwnage** [comment] 2021-10-05 17:03
Which one do you need? 
Booting High Sierra (unpatched) it defaults to "iMac":
![Screen Shot 2021-10-05 at 18 57 36](https://user-images.githubusercontent.com/37907566/136069220-730c0541-33aa-4e81-8857-375e9096cd23.png)

I guess the one Big Sur defaults to is spoofed, as it's called "iMaciMac":
![Screenshot 2021-10-05 at 18 55 05](https://user-images.githubusercontent.com/37907566/136069363-da543bd4-6a61-4599-9f11-c03fc5cbcd23.png)

**Comment by Ausdauersportler** [comment] 2021-10-05 17:16
Thanks fro helping. I have added your panel model number 9cd6 to the list in the attached copy of the BacklightInjector.kext. 
Please try and report back if the problem has been resolved.
[BacklightInjector.kext.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/7287864/BacklightInjector.kext.zip)
..

**Comment by kwnage** [comment] 2021-10-05 17:36
I replaced the one from OCLP 0.2.5 with the new BacklightInjector.kext.
Looks like it's working fine now with full brightness. :) Fantastic!

> Thanks fro helping.
Thank you guys for making all this possible in the first place :)

**Comment by khronokernel** [comment] 2021-10-05 17:38
Good to hear, will close this issue once merged into mainline
@Ausdauersportler Thank you for taking time to check on this

**Closed** 2021-10-05 17:49 UTC
Labels: bug, back-end
