### ISSUE TITLE
A required firmware update could not be installed during updating (macOS Update Assistant)

### ISSUE THREAD

**Issue by IdvFR59** [dortania/OpenCore-Legacy-Patcher#871] opened 2022-01-05 09:21 UTC
### Machine Model

MacPro4,1

### Application Version

Latest Release

### Application Variant

CLI (Command Line Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Other/Non-Applicable

### What is the Issue?

During installation phase after rebooting, for finishing installation, a firmware update blocked the finalisation of installation, with the message : 

A required firmware update could not be installed during updating (macOS Update Assistant)

![IMG_5095](https://user-images.githubusercontent.com/80541893/148192814-26c3bc5e-c9a9-4a2c-b37f-b546011c8d07.jpeg)

### Any Additional Information

SSD SIP disabled
Video Card NVIDIA GeForce GTX 680 2 Go Metal Apple Edition
32Go Ram

**Comment by Ausdauersportler** [comment] 2022-01-05 09:31
This is a duplicate of #758

**Closed** 2022-01-05 19:58 UTC
Labels: bug
