### ISSUE TITLE
USB Bootable Drive not an Option After running Build OpenCore

### ISSUE THREAD

**Issue by BigSteveLittle** [dortania/OpenCore-Legacy-Patcher#320] opened 2021-06-21 08:25 UTC
**Describe the bug**
After creating the bootable USB drive, the OpenCore app does not recognise the bootable USB.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create the bootable USB drive via Terminal
2. Open the 'OpenCore-Patcher.app'
3. select option 1. to run the build for the specific Mac
4. B to go back
5. select option 2. 'Install OpenCore to USB'
6. The USB drive does not show as an option
7. USB appears in 'Disk Utility
7. tried restarting Mac and running the 'OpenCore-Patcher.app' again, the same result

**Screenshots**

**Build Folder**
If applicable, add the generated OpenCore Build to help explain your problem.

**Hardware (please complete the following information):**
 - OS Running (ie. macOS 10.15.6, Catalina)
 - OS Patching (ie. macOS 16.6.01, Big Sur)
 - Model Patching (MacPro5,1) Flashed from (MacPro4,1)

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer](https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true) and send the output
* Attached.

**Additional context**
looking at the YouTube comments 2 or 3 other people appear to have the exact same issue.

Thanks
Steve
![2021-06-21-screen-shot-build-config-other-info](https://user-images.githubusercontent.com/34790235/122730023-21a44e00-d2bd-11eb-8323-11ded294071b.jpg)
[2021-06-21-opencore-patcher-app- issue-no-recognise-usb.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6685140/2021-06-21-opencore-patcher-app-.issue-no-recognise-usb.txt)

**Comment by dhinakg** [comment] 2021-06-21 12:20
The output of ```diskutil list``` please?

**Comment by harrythecoolb** [comment] 2021-06-21 21:47
the issue is you are using gpt prtitioning scheme reformat it in disk utilituy as mbr +mac os extended jornalled then use terminal to createt the usb and the issue will be fixed

**Comment by harrythecoolb** [comment] 2021-06-21 21:48
> the issue is you are using gpt prtitioning scheme reformat it in disk utilituy as mbr +mac os extended jornalled then use terminal to createt the usb and the issue will be fixed

(i made the same mistake thats how i know)

**Comment by BigSteveLittle** [comment] 2021-06-22 00:24
Thanks, @harrythecoolb Will try it again.

Hi, @dhinakg for the record I'll do this Before I try it again.

Thanks :)

**Comment by BigSteveLittle** [comment] 2021-06-22 03:03
Hi, it did not work (exactly the same issue) so I have attached the full readout of the disk list.

Question: The USB shows up as an 'FDisk_partition_scheme' rather than a master boot record, is this correct? Maybe my USB is miss formated.

Thanks
[2021-06-22-diskutil-list.txt](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6690695/2021-06-22-diskutil-list.txt)

/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *30.8 GB    disk3
   1:                  Apple_HFS Untitled 2              30.8 GB    disk3s1

**Comment by khronokernel** [comment] 2021-06-22 03:05
USB must be formatted as GUID partition map as our documentation lists:
https://dortania.github.io/OpenCore-Legacy-Patcher/INSTALLER.html#building


![](https://dortania.github.io/OpenCore-Legacy-Patcher/assets/img/format-usb.d6438596.png)

**Closed by khronokernel** 2021-06-22 03:05 UTC

**Comment by BigSteveLittle** [comment] 2021-06-22 03:42
Hi, 

Thanks for this it worked following documentation. I was actually following a popular video. I won't both linking to I'll just tell people in the youtube comments to follow the documentation you linked.

Steve
