### ISSUE TITLE
It doesn't open in macbook5,1 OSX El capitan

### ISSUE THREAD

**Issue by tiziodcaio** [dortania/OpenCore-Legacy-Patcher#105] opened 2021-03-16 12:16 UTC
**Describe the bug**
The terminal opens and then crashes immediatly

**To Reproduce**
1. Open app
2. See error

**Build Folder**
No one

**Hardware (please complete the following information):**
 - OS Running MacOS 10.11.6
 - OS Patching No One
 - Model Patching Macbook5,1

**Additional context**
Logs:
[3942] Error loading Python lib '/var/folders/s_/zvrcmlg92kgfcg4q92jkpk4m0000gn/T/_MEIjlzHQA/Python': dlopen: dlopen(/var/folders/s_/zvrcmlg92kgfcg4q92jkpk4m0000gn/T/_MEIjlzHQA/Python, 10): Symbol not found: _clock_getres
  Referenced from: /var/folders/s_/zvrcmlg92kgfcg4q92jkpk4m0000gn/T/_MEIjlzHQA/Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/s_/zvrcmlg92kgfcg4q92jkpk4m0000gn/T/_MEIjlzHQA/Python
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by dhinakg** [comment] 2021-03-16 12:18
Duplicate of #98

**Closed by dhinakg** 2021-03-16 12:18 UTC
