### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SulimanMukhtar** [dortania/OpenCore-Legacy-Patcher#369] opened 2021-07-07 06:43 UTC
### Machine Model

MacBookPro8,2

### Application Version

0.2.2 (Latest Release)

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Hey , Thank You For Your Efforts Of Allowing Us To Experience MacOS11 On Our Old Devices. 

Lets Start .

I've Followed Everything [Here](https://dortania.github.io/OpenCore-Legacy-Patcher/INSTALLER.html#downloading) .
The Installing Process on The laptop where very Laggy .
I did the Post-installation but before I install the patches almost everything was working fine except the brightness issue due to the graphics kext (I guess) .. can't control the brightness and don't want to use 3rd parties if possible.

The issue is after I installed the patches and restarted , my screen becomes so weird (flickers and wrong positioning of some icons on the control center) and my backlight of my keyboard doesn't work anymore .

before the patch :
      _brightness control not working
      backlight working 
      screen looks cool like it supposed to ._

after the patch :
      _brightness not working
      backlight not working
      screen looks awful_

same things happen when I disable the dGPU as described [Here](https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#wake-from-sleep-heavily-distorted-on-amd-ati-in-macos-11-3-and-newer) 

when I disable it =: after the patch
enable =: before the patch

.

what I want is to make both graphics works at the same time if possible so my brightness control works and improves performance .

Thanks Again like A Lot

**Comment by SulimanMukhtar** [comment] 2021-07-07 06:46
Also sleep doesn't work even when I close the lid

**Comment by Ausdauersportler** [comment] 2021-07-07 06:52
This is (probably just another / a) duplicate of issue #108 

You could have checked the open issues and the online docs before posting this.

https://dortania.github.io/OpenCore-Legacy-Patcher/MODELS.html

and

https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#downloading-older-non-metal-apps

**Comment by SulimanMukhtar** [comment] 2021-07-07 07:16
Hey , I checked them all earlier but seems like there’s no fix , right ?

**Comment by SulimanMukhtar** [comment] 2021-07-07 07:17
Device doesn’t sleep and brightness control not working

**Comment by Ausdauersportler** [comment] 2021-07-07 09:13
Just the fact that there is an open issue means that there is no current solution. Otherwise this issue would have been closed.

**Closed** 2021-07-07 09:17 UTC
Labels: bug

**Comment by Ausdauersportler** [comment] 2021-07-07 09:45
Check this channel on Discord: https://discord.gg/Hdk62Fg4
