### ISSUE TITLE
Best practice / procedures to maintain an OCLP install?

### ISSUE THREAD

**Issue by houser42** [dortania/Opencore-Legacy-Patcher#64] opened 2021-02-20 09:48 UTC
Hello,

Happy user here, just looking for best practice procedures to try to maintain an OCLP install.

I have used Open Core Legacy patcher 0.0.11 to install OC 0.6.6
(that is what the build folder says) on a Macbook Pro mid 2012 retina 10,2.
I bought a Broadcom BCM94360CSAX wifi/bluetooth car on ebay and installed
and all is working very well so far. Very happy with that and this splendid OC patcher!

In short, I wanted to know what the procedure should be to maintain this install in the long haul?
I have come across other people asking similar questions, so this is a small attempt at consolidating
some of the questions people seem to have. So far this has been stable enough to start thinking about using it as
an everyday working computer, but perhaps that is too optimistic? Would really appreciate realistic advice.

Some of the questions I have and have seen asked by non-super-techie people:

1. If it is working as is should we just leave it or should we update to later versions of OCLP/OC as we go along?

2. What is the safest best practice procedure for updating the OC build folder?
Just using the latest version of this patcher and reinstall on top. Or delete and reinstall?
Build a new folder, edit the config.plist when needed before using the patcher to install it?

3. At some point some would probably like to turn off the verbose logging if the setup stays stable.
What is best practice for that? Build a new folder, edit the config.plist before using the patcher to install it again?
Or some other way via mounting an editing the files on the efi boot?

4. The firmware bricking issues that some people have seen with OTA updates, what can we do to try to avoid it?
Is that risk still high? Is it possible to really brick it beyond the semi-bricking that requires the unplug-the-battery procedure fix?
Grateful for any hints! Many thanks for your great work!

**Comment by Ausdauersportler** [comment] 2021-02-20 10:17
1. and 2.
Check the ongoing discussion and if major upgrades to OC have been achieved to an update. Download, create new EFI and replace the old completely. Never mix!
3. Edit the config.plist in your created EFI folder. Do not mess with the package downloaded. Drop the -v after testing. Let it in place after upgrade and delete it after testing.
4.  You should read the OpenCore docs. With 0.6.6 a new safety belt MaxBIOSVersion has been introduced. But unsupported remains unsupported and their will be always a risk associated with using unsupported software on your Mac. If you cannot take it you will have to buy a new supported one.

**Comment by houser42** [comment] 2021-02-20 10:25
Thanks @Ausdauersportler !

1. so best procedure is to just run the OCLP again and it will replace the old build folder?

I appreciate the advice an am aware of the risks. 
It just works so well right now that I might be lulled into a false sense of stability ;)
Many thanks

**Comment by Bmju** [comment] 2021-02-20 10:35
> The firmware bricking issues that some people have seen with OTA updates, what can we do to try to avoid it?
Is that risk still high? Is it possible to really brick it beyond the semi-bricking that requires the unplug-the-battery procedure fix?

Short answer: No, it is not possible to brick beyond the semi-brick that requires the unplug-the-battery procedure. That is the brick in question, and it has been blocked now.

Longer answer: Sometimes people don't seem to understand this, but OpenCore adds NOTHING to your system. It does not, somehow, replace the BIOS. It just boots before the OS boots, and because it intervenes so early it can override and provide lots of BOIS features. But if you never boot it, it never does anything. The semi-brick issue was caused by the Apple updater having a new and enthusiastic algorithm for deciding what firmware updates to apply. The OC community had to find a way to block this. It is always possible that in future Apple will yet again update their BOIS updater, and will yet again attempt to apply an incompatible firmware update to the BIOS of any machine with anything spoofed or faked about it† (with unknown and possibly bad results); and something or other *has* to be spoofed or faked, to run an incompatible OS. The issue is not really specific to OC as a way of running an incompatible OS; that it happened on OC, not the patcher, is - I think - as much chance as anything. OC had got OTA updates working. No one on the patcher had figured out how to (it might not even be possible, on the patcher - at least not without totally stealing and illegally using Apple copyright security certificates, which is never going to happen). Because that OS feature was WORKING when using OC, the new Apple update procedure applied.

†It is worth noting that in this case the changes to Apple's firmware updater were also - notoriously - bricking or semi-bricking some completely supported, completely unmodified older Macs, too!

**Comment by houser42** [comment] 2021-02-20 21:45
Thanks for the comments, much appreciated and very helpful!
As far as I am concerned you can close the thread.

**Comment by dhinakg** [comment] 2021-02-20 23:38
1. We haven't really decided what we are going to officially advise yet, but we are leaning toward updating when you do major updates or if we suggest to (ie. if we fix a major bug). Paging @khronokernel here.
2. We are working on a proper updater which will require a few decisions made before we can implement it. For now, you can mount your EFI (or find the build folder), find the config.plist, and copy the SMBIOS values somewhere. Then rebuild the EFI with the latest patcher and either:
	a. Copy the values into the config.plist in the build folder before you install it with the patcher.
	b. After installing the EFI, mount the EFI and copy the values into the config.plist on the EFI.
3. The GUI should be reenabled with the latest patcher and on our `py3` branch. Having an easy way to toggle debug output for troubleshooting as well as being able to mount the EFI more easily is also on the roadmap.
4. The firmware bricking issues were due to an Apple bug. It should be fixed now, but there is always a risk that an Apple bug or a bug in OpenCore/other tools will cause it to occur again, but it is the same amount of risk you take by running unsupported software.

**Closed** 2021-02-24 21:50 UTC
