### ISSUE TITLE
Safari display problem with online game

### ISSUE THREAD

**Issue by newsman1979** [dortania/OpenCore-Legacy-Patcher#682] opened 2021-11-02 02:17 UTC
### Machine Model

iMac14,2

### Application Version

Latest Release

### Application Variant

TUI (Text User Interface)

### Have you verified whether this issue has been opened before? If no, your issue will be closed

true

### Is this issue with a 3rd party application?

false

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

I have a late 2013 iMac 27
I got macOS Monterey 12.0.1 installed everything seams to work fine 
the only problem I'm have is with safari, I have this game that I play on line and its not displaying the game properly and it does not work the way it should. with Big Sur (Patched Sur) it was working very smooth and the display was very good.
I have a small video to show you.

https://user-images.githubusercontent.com/56313524/139775441-7afc4464-eb55-4a59-b725-12c3d8faa4c8.mp4

but when I use chrome and play that same game it runs properly and video display is fine
and here is a small video to show you.

https://user-images.githubusercontent.com/56313524/139775672-113af9c6-efb0-4b47-9460-64827f0fca7c.mp4

like I said so far that is the only problem I have.
thank you very much for the great work you guys are doing.

**Comment by mknet1** [comment] 2021-11-04 09:08
Same here, in my case I have a problem to view javascript popups and bed leveling visualizer on OctoPrint 3d printing server host UI. I will check this issue with Monterey compatible MacBook 2018. Maybe is Safari 15.1 problem ...

**Comment by newsman1979** [comment] 2021-11-04 10:56
yes I also have the same problem with javascript popups.
safari is fine because I did test this on my 2019 MacBook Pro the game runs really smooth no problem at all.
it has to be a bug on the nividia patch that is causing this.
but I don't understand why it works fine when I play the same game on chrome.

**Comment by newsman1979** [comment] 2021-11-05 01:46
just want show you another problem OCLP on my iMac late 2013
![IMG_1880](https://user-images.githubusercontent.com/56313524/140444180-b877d2ac-8194-42ae-8acf-a2787a998997.JPG)

and this one from MBP Mid 2015 (Monterey supported)
![IMG_1881 2](https://user-images.githubusercontent.com/56313524/140444458-4c19bd33-4cc7-4237-933e-3aecd330c05f.jpg)

**Comment by newsman1979** [comment] 2021-12-16 22:08
i just did the upgrade to 12.1 with OCLP 0.3.3 and the problem still the same nothing change.
hope the great guys at OCLP can look in to this and see if there a fix.
thank you very much for the hard work you guys are doing.

**Comment by Thyssenkrupp234** [comment] 2021-12-22 01:18
First of all, CleanMyMacX is a complete scam, I would recommend uninstalling it. You have a late 2013 iMac, right? Did you go into the OCLP application and install the post-volume patches? Because I tested this menu on my 2010 iMac w/ a TeraScale 2 GPU and it looks fine. If you already installed the patches, install them again. Tell me what that does.
@newsman1979

**Comment by Thyssenkrupp234** [comment] 2021-12-22 01:24
As for the Safari issue, #108 explains an issue about Safari randomly freezing: `Safari Scroll Freezing randomly on 12.0`

This is a Monterey issue, and you may as well report this to them via discord. Safari in Monterey is obviously not as good with the OCLP patches, but Monterey was recently released and OCLP has not had as much time as they have had with Big Sur.

**Comment by newsman1979** [comment] 2021-12-22 12:58
thanks for the replay Thyssenkrupp234, for the post install patches I did that and I did that more then once. but with the same problem. for Safari I did report that on discord when the first Monterey 12.0.1 was released and I did report it again when I installed 12.1 but I did not get any response. the only response I got was to uninstall cleanmymac x and that it.

**Comment by OKonnel** [comment] 2022-01-09 09:30
Since these iMacs have a nVidia Kepler GPU, could the problems be due to the lack of OpenCL Framework support that Apple has removed in the latest System builds?
In this case, with the Post Install Patch, perhaps we should install also the missing nVidia library in the Framework and not the Kext drivers only.
This library is NVPTX.dylib in
/Frameworks/OpenCL.framework/Versions/A/Libraries/NVPTX.dylib
Perhaps we should install also libCLVMIGILPlugin.dylib and libCLVMNVPTXPlugin.dylib as well.
Perhaps this would also solve the Photoshop issue that in the Hardware Preferences requires the OpenCL drivers for the nVidia card...
The idea came to me by reading a post by ABrasilianBot in Github in which he also attaches a zip file with the three missing libraries. If that works, a big thank you to ABrasilianBot.

**Comment by newsman1979** [comment] 2022-01-10 17:01
thanks for the info OKonnel I will be trying this to see if it will fix that problem.
just a question how to install the 3 files just open /Frameworks/OpenCL.framework/Versions/A/Libraries/NVPTX.dylib and drag those files there or there is different way or what is the proper way.
thanks in advance.

**Comment by OKonnel** [comment] 2022-01-10 17:26
So, I tried this morning to insert the three files in my iMac 27'' (CPU i7 late 2013) with macOS 12.1, thanks to the intelligent and precise collaboration of [Ausdarsporter](https://forums.macrumors.com/members/ausdauersportler.1199136/), but unfortunately nothing has changed: Photoshop 2022 works fine, but it still continues to appear the warning about the absence of OpenCL.
Regarding your "CleanMyMac X" malfunction and some video glitches, however, I have no problems. Everything works very well for me, even Apple TV or Netflix with Safari.
In any case, I will still try to solve the OpenCL problem by replacing or inserting other Framework files and maybe even intervening in the Extensions.
If I am successful I will let you know, but in the meantime let's rely on the intelligent Developers of this Forum, from [Khronokernel](https://github.com/khronokernel), [Ausdarsporter](https://forums.macrumors.com/members/ausdauersportler.1199136/), to everyone else and hopefully they will resolve soon.
In fact, I verified that the Post Install Patch of OpenCore Legacy Patcher 0.3.3 had already installed two of the three aforementioned libraries. The third file was already installed by Apple and concerns the HD5000 GPU. I tried to replace it with the ABrasilianBot library concerning the HD4000 GPU, but I haven't solved it.

**Comment by newsman1979** [comment] 2022-01-10 18:20
thank you very for all the hard work you done to help people like me end user 
and I will wait for you to let me know if everything is good to go. or if you want I can try this on my Mac and let you know the result. the only thing I care about is safari with the online game problem because I don't use cleanmymac x anymore.
thanks again.

**Comment by OKonnel** [comment] 2022-01-10 18:46
Meanwhile, I anticipate the following, since these posts could also be read by good OCLP's Developers.
I just verified in Catalina (opening the files "on the fly" with TexEdit) that in OpenCL.frameworks there are several libraries where nVidia is mentioned and these libraries are not in the Monterey OpenCL Framework. For example, the "libcl2module.dylib" library in the 3425AMD subfolder also contains nVidia references. (see attached jpg)
Soon I'll try to reboot, access the disk with Monterey and try to put and / or replace all these libraries in Monterey's OpenCL.framework.
I'll let you know, hoping not to lock my computer...
![OpenCL-Catalina-10 15 7-libraries](https://user-images.githubusercontent.com/81856309/148821386-6922289a-b9e8-46fa-a6ed-e69229277ac3.jpg)

**Comment by newsman1979** [comment] 2022-01-10 18:51
I really hope everything go smooth and hope your computer will not get locked good luck bro.

**Comment by OKonnel** [comment] 2022-01-10 22:42
In fact, after putting the Catalina's nVidia kexts, Monterey restart failed and crashed.  So, I rebooted in Safe Mode, re-installed the OCLP 0.3.3 Post Install Patch and after rebooting the Mac reopened Monterey. After all this, I checked if Photoshop open the images and saw that it doesn't open them.  However, disabling the advanced options that activate the GPU (in my case the GTX 780MX) the images open and you can work.  Unfortunately, with the GPU turned off Photoshop in Monterey is visibly slower than Catalina.

**Comment by newsman1979** [comment] 2022-01-14 21:25
hello OKonnel any update, should i wait or should i try to install 12.1 on my iMac. 
12.2 will released soon hope the great OCLP guys will have i fix for this safari problem.
thanks in advance

**Comment by OKonnel** [comment] 2022-01-15 14:25
<< Should I wait or should I try installing 12.1 on my iMac? >>
Dear newsman1979, can you decide. Try to send me the link of the game that is giving you problems, so I try too, hoping that there is no need to register and / or pay. Maybe it depends on JavaScript and not on the OpenCL of the nVidia graphics card.
<< 12.2 will be released soon, I hope the OCLP big boys fix this Safari problem. >>
If the problem is related to OpenCL drivers and nVidia graphics cards it will not be easy for the OCLP guys to solve the problem. I know that most of them do not have Macs with nVidia cards and therefore they cannot test this issue.
Bye

**Comment by newsman1979** [comment] 2022-01-15 15:42
thanks for the reply OKonnel.
this game is free but you need to register the only thing this game requires is an email and that's it 
this is the link
https://en6.forgeofempires.com
thanks again

**Comment by newsman1979** [comment] 2022-01-27 01:04
just finished updating to 12.2 and everything went smooth and i notice that screen saver is working with the new OCLP 0.4.1
but the safari problem is still there.

**Comment by OKonnel** [comment] 2022-01-27 11:36
Good! Thanks for your useful informations! But I'm quarantined in my house with Covid-19 and so I won't do anything to the iMac I have in my office. Here I have a late 2010 13-inch MacBook Pro with High Sierra.
I hope that Khronokernel and others solving this problem for you but also the important OpenCL issue with Photoshop 2022

**Closed** 2023-10-02 16:23 UTC
Labels: bug
