### ISSUE TITLE
External display (Thunderbolt display) does not work with Big Sur 11.2.3 (OCLP 0.1.0)

### ISSUE THREAD

**Issue by paltrowlalic** [dortania/OpenCore-Legacy-Patcher#157] opened 2021-04-20 10:21 UTC
Hi, thank all for your excellent work. I installed Big Sur 11.2.3 using OCLP 0.1.0 on my old 2011 mid iMac (iMac12,2). Everything works and the process is very easy to follow (great documentation we got here). Sound, wifi, sleep, wifi, brightness control all work without any probem. The only problem is that the external Thunderbolt display does not work anymore. It was working with HS and Catalina. I also tried it with another MacBook Pro 2015 with Big Sur 11.2.3 installed and it worked as well. The USB and audio port on the Thunderbolt display works without problem and it is just that iMac does not recognize the display/video output. It seems that the issue is related to OCLP or the BS installed (which is less likely I suppose).  Thanks for the help in advance and I will be happy to do some testing for the topic.

**Comment by khronokernel** [comment] 2021-04-20 13:17
Hello, are you able to upload 2 IOReg's for us? Specifically with the following parameters:

* Machine running Big Sur with Thunderbolt Display attached
* Machine running High Sierra with Thunderbolt Display attached

This will give us a better idea as to where the issue may be regarding the display support. To generate an IOReg, we simply need you to run the below program, File -> SaveAs and send us the output files (.ioreg):

https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip?raw=true

**Comment by paltrowlalic** [comment] 2021-04-20 13:40
Hi Khronokernel, thanks for the reply. Please find two files attached. I tried another DELL monitor using mini-display port -> HDMI and it is working. So the problem is specific for Thunderbolt Display I suppose.
[Archive.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6343938/Archive.zip)

**Comment by khronokernel** [comment] 2021-04-20 13:41
> So the problem is specific for Thunderbolt Display I suppose.

Interesting, thanks for this information! Will look over it in a bit

**Comment by khronokernel** [comment] 2021-04-20 15:20
Could you test the below build?
[OpenCore-PIKERA.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6344655/OpenCore-PIKERA.zip)

**Comment by khronokernel** [comment] 2021-04-20 15:31
Oh no worries, the easiest way to "install" this is to mount the ESP(EFI Partition) and put OpenCore on there. To do so, simply run [MountEFI](https://github.com/corpnewt/MountEFI) and select the disk you have OpenCore already on. Then in finder, you'll see a drive called EFI show up. Just replace the old OpenCore files with the above provided. Ensure that on the root of the EFI partition are both an EFI folder and System folder from what I provided earlier

**Comment by paltrowlalic** [comment] 2021-04-20 16:04
Hi, I cannot boot into BS anymore through OC after replacing those two folders. Please find the image attached.
![img](https://user-images.githubusercontent.com/19687506/115428514-5ed75b80-a1fa-11eb-92c4-fa2b7fb08d4f.JPG)

**Comment by khronokernel** [comment] 2021-04-20 16:07
Oh looks like High Sierra corrupted the preboot signature. So delta updates are most likely botched. This is a bug with High Sierra and not OCLP for reference, there's nothing we can do and Apple won't ever fix the bug unfortunately

Regarding getting it to at least boot, enter EFI/OC/config.plist and change SecureBootModel's entry from `j137` to `Disabled`. This should resolve booting for the time being

**Comment by paltrowlalic** [comment] 2021-04-20 16:10
I can boot into HS using the normal booter and used OCLP 0.1.0 to replace the EFI folders again and now I can boot into BS without a problem. Are you suggesting if I remove the HS partition and only have BS installed and the problem might go away?

**Comment by khronokernel** [comment] 2021-04-20 16:12
> Are you suggesting if I remove the HS partition and only have BS installed and the problem might go away?

The issue is that every time you boot High Sierra, Mojave through Big Sur's SecureBoot image is broken. In Big Sur, this secure boot image is required to be intact for Delta updates to occur. To remove the issue would be to never boot High Sierra with the Big Sur drive installed at the same time

**Comment by paltrowlalic** [comment] 2021-04-20 16:19
Thanks again! Ok I am going to try and see if I have any luck with OPLP and Catalina

**Comment by paltrowlalic** [comment] 2021-04-20 16:39
Adding more information, the error msg was:

OCSB: No suitable signature - Security Violation
OCB: Apple Secure Boot prohibits this boot entry, enforcing!
OCB: Loading failed - Security Violation

I thought the Secure Boot Model has been disabled.

**Comment by khronokernel** [comment] 2021-04-20 16:40
Note that SecureBootModel's value iOS case sensitive, it must be `Disabled`. Can you send a photo how you entered it?

**Comment by paltrowlalic** [comment] 2021-04-20 16:58
: ) No I did not input any value just using OCLP to create the files so it was Disabled. I compared two config.plist files and it seems the value in the file you sent is j137 which I guess is not correct?  BTW, for the config.plist file you sent, is it for AMD or NVIDIA GPU? I have an NVIDIA one installed.

![img2](https://user-images.githubusercontent.com/19687506/115435492-cd6be780-a201-11eb-9168-93c092d69cf4.png)

**Comment by khronokernel** [comment] 2021-04-20 16:58
I requested you to edit the config:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/157#issuecomment-823405668

**Comment by paltrowlalic** [comment] 2021-04-20 17:00
aha -,- I did not see your edited comments. Will try it now!

**Comment by paltrowlalic** [comment] 2021-04-22 15:54
Hi, I did a bit more experiment yesterday. I have tried to remove HS, only installed Catalina and it seems now no matter what, the Thunderbolt display is not detected in Catalina or Big Sur. The display is detected in HS without a problem. I will try sth in the single-user mode to see what could have caused this!

**Comment by khronokernel** [comment] 2021-05-03 22:26
Closing as there's been no further progress. We have no hardware and uninterested in investing time, if you find the issue to be OCLP again feel free to comment. Have no issue reopening

**Closed by khronokernel** 2021-05-03 22:26 UTC
Labels: back-end, enhancement, waiting-for-response
