### ISSUE TITLE
[Enhancement]: Trick monterey into thinking that older macs can use low power mode.

### ISSUE THREAD

**Issue by linusrg1** [dortania/OpenCore-Legacy-Patcher#486] opened 2021-09-13 00:32 UTC
### Machine Model

MacBookPro9,2

### Application Version

Latest Release

### Application Variant

Other/Non-Applicable

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

I heard that monterey got a new low power mode, how ever it does not seem to appear on my 9,2 (probably because it is unsupported) though it would be cool if a feature were to be added to spoof macos in such a way where low power mode would be available

**Comment by educovas** [comment] 2021-09-13 00:35
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/316

**Comment by dhinakg** [comment] 2021-09-13 01:34
Duplicate of #316

**Closed by dhinakg** 2021-09-13 01:34 UTC
Labels: bug
