### ISSUE TITLE
Graphical bugs in apple music, Imessage sluggish

### ISSUE THREAD

**Issue by jherm810** [dortania/OpenCore-Legacy-Patcher#273] opened 2021-06-08 04:37 UTC
I'm running a 2011 macbook pro 2011 on a ssd. I'm using the expiremental drivers and imessage is super sluggish and the control center and music app have weird graphical bugs, else works great so good job guys! Please email me if you'd like screenshots and video proof of these issues.

**Comment by Tiger-AC** [comment] 2021-06-08 05:14
I have a similar issue on a Late 2009 21.5" iMac (10,1) with E8600 C2D & GeForce 9400 (on board with 256MB shared RAM) GPU, along with 12 GB RAM and 1GB Fusion Drive (500GB SSD and 500GB HDD).
The issue is that iMessage and Apple Map are very sluggish (100% CPU usage). 

The Photo App distortion issue has been resolved in v 0.1.6 - well done and much appreciated.
Note: I did not try the music app... and went back to DosDude1's Catalina, which runs very smoothly on my 12 year old iMac.

**Comment by jherm810** [comment] 2021-06-08 10:57
Imessage seems to only use 40% of my cpu at most when it first opens is the weird part. And the music app bug is the distortion around the mouse when i drag it on the edges to say,idk, pick the shuffle option. Its gotta be something software related as the CPU is barely used in both Apple Music and Imessage. The dials in control center also render weirdly, hopefully this can get fixed for the next release.

**Comment by khronokernel** [comment] 2021-06-08 17:34
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/108

**Closed by khronokernel** 2021-06-08 17:34 UTC
