### ISSUE TITLE
Cannot correctly identify the iMac 5K resolution in nightly 0.1.7

### ISSUE THREAD

**Issue by 473072010** [dortania/OpenCore-Legacy-Patcher#283] opened 2021-06-10 02:58 UTC
**Describe the bug**
I had tried to install macOS Monterey on my late 2014 iMac 5K using the patcher. Every things worked fine but i found an issue that is the system cannot recognize my screen resolution. 
In the "about my Mac:">"Display" the system recognize my display is "Built-in Retina Display 27-inch (3840×2160)" not the 5120×2880
But in the system report the Graphic/Display label the screen resolution shows correctly. it shows
Displays:
iMac:
  Display Type:	Built-In Retina LCD
  Resolution:	Retina 5K (5120 x 2880)
  Framebuffer Depth:	30-Bit Color (ARGB2101010)

**Screenshots**
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/47414246/121455886-c7131400-c9d7-11eb-8b9b-763f2f7dfe73.png">

**Build Folder**
[OpenCore-RELEASE.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6628063/OpenCore-RELEASE.zip)

**Hardware (please complete the following information):**
 - OS Running  (macOS Monterey 12.0 beta 1)
 - OS Patching (macOS Monterey 12.0 beta 1)
 - Model Patching (iMac15,1)

**Comment by VKondakoff** [comment] 2021-06-10 06:42
I have exactly the same issue on the same hardware.

**Comment by maxwell1500** [comment] 2021-06-11 00:37
Unless I am mistaken on the issue the 5k display of 5120x2160, is scaled to 3840 x 2160, if you go to display and select more space or less it should change the scale.  So it should be 5120x2160 resolution with everything larger to be easier to read.  If you install RDM it will let you select more resolutions.

**Comment by 473072010** [comment] 2021-06-11 02:30
> Unless I am mistaken on the issue the 5k display of 5120x2160, might be scaled to 3840 x 2160. Does it change if you change the scaling? If you install RDM it will let you select more resolutions.

At first I change the resolution using RDM the screen resolution change to 5120 × 2880, the image and word shown on display are still not clearly, just smaller than before. After I change my EFI to [big-sur-micropatcher](https://github.com/barrykn/big-sur-micropatcher) EFI then the resolution back to normal, maybe you can get any inspire from that?

**Comment by khronokernel** [comment] 2021-06-11 16:38
Could you please verify whether the below build restores the 5k output?
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2973699269/artifacts/67065216

**Comment by VKondakoff** [comment] 2021-06-11 17:34
No, after installing the EFI from flash card and proceeding to load the OS from HD it hangs right after showing the apple logo. The progress bar does not even appear. 
Now I’m a little bit stuck (writing fro iPad). Is there a way to review the system? Thanks!

**Comment by khronokernel** [comment] 2021-06-11 17:40
@VKondakoff I assume you have a native OS to boot back to without OpenCore, can you try installing the below build and try booting Monterey again?

https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2974156558/artifacts/67078936

**Comment by VKondakoff** [comment] 2021-06-11 19:52
Unfortunately it was the only OS on this machine. ;( Right now I’m installing  Big Sur from recovery to another volume. Will come back after the process finishes.

**Comment by VKondakoff** [comment] 2021-06-11 20:44
I downloaded the latest build and booted Monterey with the new EFI. Unfortunately, the issue is still there:

<img width="584" alt="Снимок экрана 2021-06-11 в 23 40 43" src="https://user-images.githubusercontent.com/230824/121746679-e6f92380-cb0e-11eb-8156-22be008bb25a.png">

**Comment by VKondakoff** [comment] 2021-06-11 21:01
The behaviour changed a bit. Now the EFI booting Apple logo is a little bit bigger, than the one when booting to Big Sur. In the previous build it was different: first the logo was a bit _smaller_ than the Big Sir one, and in the middle of booting it jumped to a _bigger_ one. With the new build the logo does not change it's size while booting.

Big Sur Apple logo:
![IMG_2126](https://user-images.githubusercontent.com/230824/121748112-1f99fc80-cb11-11eb-81de-320c1914849f.JPG)

Monterey Apple logo:
![IMG_2125](https://user-images.githubusercontent.com/230824/121748197-393b4400-cb11-11eb-8803-746b419edaa4.JPG)

(Sorry for the photos quality).

**Comment by khronokernel** [comment] 2021-06-11 21:12
Hmm unfortunate, seems there's some hard coded logic for iMac15,1's display controller. Grepping Big Sur's Kexts for matching board IDs:

```
./ApplePlatformEnabler.kext/Contents/MacOS/ApplePlatformEnabler
./AppleGraphicsPowerManagement.kext/Contents/Info.plist
./AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist
```

Currently we do override AppleGraphicsPowerManagement.kext's defined map, however we do not for AppleGraphicsDevicePolicy.kext. Below you'll find a build that overrides it:

https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2975653206/artifacts/67120489

**Comment by VKondakoff** [comment] 2021-06-11 22:00
> After I change my EFI to [big-sur-micropatcher](https://github.com/barrykn/big-sur-micropatcher) EFI then the resolution back to normal, maybe you can get any inspire from that?

The topic starter mentioned there is a patch that fixes the issue. So, looks like it is possible somehow?

**Comment by khronokernel** [comment] 2021-06-11 22:04
> The topic starter mentioned there is a patch that fixes the issue. So, looks like it is possible somehow?

There is no patch, reason micro patcher works is it does nothing with the SMBIOS. OpenCore Legacy Patcher spoofs to a supported Mac (ie. iMac17,1, late 2015 model) to gain native OTA update support

To fix this, we need to determine where in macOS the Display Control quirks are coded and patch our new SMBIOS into it

**Comment by VKondakoff** [comment] 2021-06-11 22:10
Got it. So, the issue is reproducible on my machine, I’m ready to test something when you need it.

**Comment by khronokernel** [comment] 2021-06-12 03:15
Please try this build:

https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2977136383/artifacts/67163690

However, before building OpenCore please go into `Patcher Settings -> Advanced Settings -> Override SMBIOS Spoof` and set `Disable all spoofing`. This should set our patcher to micro patcher-esque so helps us know where the issue lies

**Comment by VKondakoff** [comment] 2021-06-12 07:33
Hmm.. Not sure everything OK here. 
Here is what I get when trying to Disable all spoofing:

Valid options:
1. Default set by OpenCore (Default)
2. User Override
3. Disable all spoofing (unsupported configuration)
        
```
Set SMBIOS status: 3
Disabling SMBIOS spoof
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 252, in <module>
  File "OpenCore-Patcher.command", line 246, in main_menu
  File "Resources/Utilities.py", line 182, in start
  File "OpenCore-Patcher.command", line 111, in patcher_settings
  File "Resources/Utilities.py", line 182, in start
  File "OpenCore-Patcher.command", line 136, in advanced_patcher_settings
  File "Resources/Utilities.py", line 182, in start
  File "Resources/CliMenu.py", line 438, in set_smbios
AttributeError: 'MenuOptions' object has no attribute 'current_model'
[961] Failed to execute script OpenCore-Patcher
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

What should I do?

**Comment by khronokernel** [comment] 2021-06-13 18:32
Apologies, please try this build:
https://github.com/dortania/OpenCore-Legacy-Patcher/suites/2983544892/artifacts/67334171

**Comment by khronokernel** [comment] 2021-06-13 20:20
Apparently this is a known issue and hasn't been fixed since the 5k iMac launched:
https://askubuntu.com/questions/866920/limited-resolution-booting-with-refind-on-imac-5k

Other boot loaders also are affected, not just OpenCore so not entirely sure what's the best way to proceed

**Comment by jonblatho** [comment] 2021-06-13 23:59
Running into this issue as well on my iMac15,1. I’ve also tried SwitchResX as it seemed like a potential stopgap solution to force macOS to correctly recognize the 5120×2880 display and show the corresponding resolution options, but so far I’ve been unsuccessful in getting to the correct configuration to make it happen, and it doesn’t automatically persist across a reboot.

Not sure if it’s helpful information at all, but while tinkering with SwitchResX I was able to get it to show other…interesting combinations of display sizes and resolutions, including some resolutions even higher than 5K (one such combination was 18" @ 7680 × 4320). Through that it would appear that there might be _some_ hope — but it might be outside the scope of this project.

**Comment by OKonnel** [comment] 2021-06-16 07:05
Hoping to help, I try to give my opinion as a passionate nerd, not a developer, although I don't know if what I see in the code (e.g.: build.py file) is an error or not.
In the build.py files I have seen that some names are written without the comma and among them also yours: "iMac151" instead of iMac "15.1". But, again, I point out that I am unable to tell if this is interfering with your problem. I'm sorry...
If this is an oversight in the build, there may be other files affected as well.

**Comment by jonblatho** [comment] 2021-06-16 21:40
@OKonnel Sadly from what I’ve seen in the Discord it looks like the issue runs *much* deeper than that and is related to lower-level code — like driver-level stuff — needed for macOS to correctly address iMac15,1’s display. This is backed up by drivers not being available for other OSes (except Windows) running on iMac15,1, where they can only go up to 4K.

Perhaps someone with more technical knowledge in this area can weigh in with more detail, but I got the impression that it will take a *lot* of work to get to a resolution on this issue, if a fix is possible at all.

**Comment by OKonnel** [comment] 2021-06-17 08:04
Dear @jonblatho , we hope Apple solves your problem.
Maybe it helps you to know that in my case Big Sur crashed my Apple TV purchased movies and never got Photo Booth fully working.
So, some very experienced users attributed the problems to not supporting my Video Card (nVidia GTX 780M 4GB, top card for 27 '' late 2013 iMacs with i7 CPU) and I ended up believing that my iMac really was obsolete and to change.
Then, instead, I install Monterey and everything starts working better than ever.
To better understand, from an internal analysis of the Kext packages of nVidia cards, I realized that some Kext for nVidia was missing the binary file contained in .kext/Contents/MacOS/ ... The fact is that also missing in Monterey, but now my iMac has no more problems and the accelerations are all active and perfect.
With the help of the good @Ausdauersportler I was already preparing to put some Catalina drivers in Big Sur and instead, as you can see, the block of some functions was hidden from who knows where else.
So! I would therefore suggest that you report the issue to Apple anyway, using Feedback Assistant. Maybe they won't take this into account, as your iMac is no longer supported (and it's a crime... :-( ), but maybe, if that's part of a bug like maybe it was with my problem in Big Sur, by fixing your problem Apple know they will improve Monterey anyway and not to cause trouble to supported users.

**Comment by owenzhao** [comment] 2021-07-01 06:41
I just installed macOS Monterey 12 beta 2 on my iMac 5K 2014 late. I installed it in an external SSD. However, for convenience, I installed this patcher to the EFI of the internal SSD. 

What I didn't expected was that after that, macOS Big Sur 11.4 on the internal SSD, the display resolution was changed to max 3840x2160 as well. Is there a way to reverse the process other than reinstall the system? Thanks.

**Comment by owenzhao** [comment] 2021-07-02 01:26
> I just installed macOS Monterey 12 beta 2 on my iMac 5K 2014 late. I installed it in an external SSD. However, for convenience, I installed this patcher to the EFI of the internal SSD.
> 
> What I didn't expected was that after that, macOS Big Sur 11.4 on the internal SSD, the display resolution was changed to max 3840x2160 as well. Is there a way to reverse the process other than reinstall the system? Thanks.

I just solved my own issue. 

Follow this article. https://www.macobserver.com/tips/quick-tip/macos-removing-windows-efi-boot-entry/

I found that the new EFI partition that created by Apple's `Disk Utility.app` just contains no contents. So mount the EFI by this patch and `rm -fr *` could just make everything back.

In this way, I am wondering if there is removing all GPU related driver or settings for iMac 5K on this patch, will the original resolution work on macOS Monterey by default?

**Comment by khronokernel** [comment] 2021-07-04 19:13
Closing as consolidated information here:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/359

**Closed by khronokernel** 2021-07-04 19:13 UTC
Labels: back-end, bug, help wanted
