### ISSUE TITLE
gpu-power-prefs var detection shouldn't be case-sensitive

### ISSUE THREAD

**Issue by airman1951** [dortania/OpenCore-Legacy-Patcher#248] opened 2021-05-26 13:05 UTC
**Describe the bug**
The macOS 11.4 breaks the fixes for brightness control and sleep in MBP8,2 (Intel HD300 and AMD HD6750M (disabled)).

**To Reproduce**
Missing brightness control both in SysPref and in Control Center.  No sleep closing the lid and system breaks when sleep is invoked by apple menu. The system goes to sleep but doesn't wake up. It is still alive (keyboard backlit is on and fans are working, but the display doesn't turn on.

**Screenshots**
![Screenshot 2021-05-26 at 14 50 41](https://user-images.githubusercontent.com/77781242/119663558-bdfc4180-be32-11eb-84f8-c800a4596c1d.png)

**Build Folder**
[Build-Folder.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6546853/Build-Folder.zip)

**Hardware (please complete the following information):**
 - macOS 11.4 20F71
 - MBP8,2 

For in-depth hardware logs, we highly encourage users to run [IORegistryExplorer]
[Nando’s MacBook Pro.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6546843/Nando.s.MacBook.Pro.zip)

**Additional context**

**Comment by airman1951** [comment] 2021-05-27 12:02
No way.  I did a clean installation, apply the root volume patches, reapply the jackluke's nightshift patch, and brightness control is still missing. I hope the team could find a solution..;-).

[Nando’s MacBook Pro.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6553786/Nando.s.MacBook.Pro.zip)

**Comment by lexcroftdev1** [comment] 2021-05-27 19:08
same here. Brightness controls, Keyboard Backlite and sleep wake issues. The last one is really deal breaker. 
I have also noticed that laptop runs really hot as the AMDRadeonX3000.kext file is missing

**Comment by lulujyc** [comment] 2021-05-28 07:29
Try resetting NVRAM and adding the NVRAM command again. The fix should be irrelevant between OS minor upgrades...(but I haven't upgraded to 11.4 yet so it's just my best guess)

**Comment by lulujyc** [comment] 2021-05-28 07:44
I would suggest to try using my patched 0.1.4 OCLP to control the variable to see if the problem is brought by OCLP upgrades or macOS. Personally, OCLP 0.1.5+ didn't work very well for me, sometimes resulting in a kernel panic booting the OS. Since my current EFI and patcher works fine I haven't spend a lot of time into it.

My patched OCLP full package can be found here: https://fromsmash.com/KH2Eq~gZ4I-dt

**Comment by airman1951** [comment] 2021-05-28 08:25
Resetting nvram doesn't help.  How to apply your modified package?  Rebuild the EFI only or apply the root volume patches?

**Comment by lulujyc** [comment] 2021-05-28 08:28
> Resetting nvram doesn't help. How to apply your modified package? Rebuild the EFI only or apply the root volume patches only or both?

Both

**Comment by airman1951** [comment] 2021-05-28 08:59
And of course still sleep is working now!

**Comment by lulujyc** [comment] 2021-05-28 09:34
Glad to hear that it works. Seems like that newer versions of OCLP reverted the working status of the brightness patch.

**Comment by lulujyc** [comment] 2021-05-28 09:35
So the issue is not macOS 11.4 breaking brightness control fixes. It is OCLP brightness fixes now being non-working, no matter the OS version :) maybe you want to change the issue title

**Comment by lexcroftdev1** [comment] 2021-05-28 09:35
can you confirm if the keyboard backlite is also working?

**Comment by lulujyc** [comment] 2021-05-28 09:36
> can you confirm if the keyboard backlite is also working?

keyboard backlight is another issue. use lab tick.

**Comment by airman1951** [comment] 2021-05-28 12:18
I did further tests.  It seems that EFI is not an issue: I restarted with 0.1.6 EFI and everything works as expected.

**Comment by guanzhangrtk** [comment] 2021-05-28 12:30
So are you saying there's actually no issue after updating to 11.4 just need to re-run OCLP post-install and we're good?

**Comment by airman1951** [comment] 2021-05-28 12:59
> So are you saying there's actually no issue after updating to 11.4 just need to re-run OCLP post-install and we're good?

With the official 0.1.6 root volume patches you loose the brightness control and the sleep functionality.  With the lulujyc's modified patches it seems that all the functionalities are working.

**Comment by khronokernel** [comment] 2021-05-28 13:04
@airman1951 Were you ever able to verify if 0.1.5 worked? We reworked the root patch system in 0.1.6 so would appreciate knowing where the issue may have been introduced

**Comment by airman1951** [comment] 2021-05-28 13:07
OK. I'm going to test it.

**Comment by airman1951** [comment] 2021-05-28 13:25
Next step was to reapply 0.1.6.  And brightness is still there.  Definitely the kexts introduces by lulujyc makes the difference.

**Comment by lulujyc** [comment] 2021-05-28 14:16
Maybe you want to try reinstalling macOS 11.4 (which doesn't harm your data but only touches the system partition) to make the OS clean. Very good news that Apple didn't make us old Mac users angry (again😂)

**Comment by airman1951** [comment] 2021-05-28 14:21
> Maybe you want to try reinstalling macOS 11.4 (which doesn't harm your data but only touches the system partition) to make the OS clean. Very good news that Apple didn't make us old Mac users angry (again😂)

You're right. Maybe later this night.

**Comment by airman1951** [comment] 2021-05-28 17:06
I reinstalled 11.4 and applied the OCLP 0.1.5 volume patches.  I confirm that even 0.1.5 fails to load brightness control.  Only working fix is the modified OCLP 0.1.3 by lulujyc.

**Comment by khronokernel** [comment] 2021-05-28 17:09
Could you elaborate what kexts are installed with 0.1.5? Currently our patches are identical to 0.1.4, though 0.1.5 has extra hardware checks:

https://github.com/dortania/OpenCore-Legacy-Patcher/blob/0.1.5/Resources/SysPatch.py#L135-L149

With idevice on Discord, we determined the patch set should be as follows:
```python
#- deMUX: Don't need the AMD patches                    
#- dGPUs enabled:  Don't install the AMD patches (Infinite login loop otherwise)                   
#- dGPUs disabled: Do need the AMD patches (Restores Brightness control)
```

**Comment by airman1951** [comment] 2021-05-28 17:15
Sorry, what exactly I have to do ? I tried $idevice in Discord without result.

**Comment by khronokernel** [comment] 2021-05-28 17:15
idevice is a user on discord that helped determine the current TeraScale 2 patch logic

**Comment by guanzhangrtk** [comment] 2021-05-28 17:16
idevice is @lulujyc's Discord username as far as I recall

**Comment by airman1951** [comment] 2021-05-28 17:19
Sorry, my knowledge of Discord is less then basic..

**Comment by airman1951** [comment] 2021-05-28 17:23
Anyway my MBP8,2 is in dGPUs disabled category

**Comment by airman1951** [comment] 2021-05-29 06:19
Found the issue. Look the output of root volume patches.
![Screenshot 2021-05-29 at 08 13 46](https://user-images.githubusercontent.com/77781242/120060121-3131cd80-c056-11eb-8bd5-19642d95a67d.png)
This is the script I always used to disable the dGPU
![Screenshot 2021-05-29 at 08 15 25](https://user-images.githubusercontent.com/77781242/120060136-4a3a7e80-c056-11eb-9c34-7988fb738bea.png)
Are capital letters the culprit?

**Comment by airman1951** [comment] 2021-05-29 06:26
Yes, they are. I uppercased my script...
![Screenshot 2021-05-29 at 08 25 45](https://user-images.githubusercontent.com/77781242/120060333-84f0e680-c057-11eb-93ca-eb81f35889f8.png)

**Comment by airman1951** [comment] 2021-05-29 06:29
Thanks to everybody for the help and the patience.

**Comment by lexcroftdev1** [comment] 2021-05-29 16:43
will nvram understand upper cased FA4CE28D-B62F-4C99-9CC3-6815686E30F9 or you have to rerun the script after applying the patch?

**Comment by airman1951** [comment] 2021-05-29 17:19
> will nvram understand upper cased FA4CE28D-B62F-4C99-9CC3-6815686E30F9 or you have to rerun the script (with lowercase) after applying the patch?

If you have already applied nvram with the uppercase parameter you are OK and no action is required by your side.  My problem was that my nvram setting was originally done with lowercase parameter.  I reapplied the nvram uppercased and AFTER that the root volume patcher recognized the dGPU disabled. The script DOESN'T run with lowercase parameter.

**Comment by lexcroftdev1** [comment] 2021-05-29 18:18
yes that's because in the source code it compares with the upper case (here: https://github.com/dortania/OpenCore-Legacy-Patcher/blob/0.1.5/Resources/SysPatch.py#L135-L149).  

my question is nvram with upper case will actually work and disable the AMD GPU or not?  if nvram does not recognize the uppercase (which i dont know) then we may have to run this script again with lower case

**Comment by airman1951** [comment] 2021-05-29 22:06
The answer of your question is YES. Don't use the lowercase.

**Comment by guanzhangrtk** [comment] 2021-05-30 02:15
> The answer of your question is YES. Don't use the lowercase.

This sounds like a bug because the official documentation's example uses lower case: https://dortania.github.io/OpenCore-Legacy-Patcher/ACCEL.html#unable-to-achieve-gpu-acceleration-on-2011-15-and-17-macbook-pros

Also, I've always ran the nvram command in lower case and didn't have issue with the patcher I downloaded, however at this point I'm not sure which version I used. I don't think the code has changed since initially committed so not exactly sure what's going on here...

**Comment by khronokernel** [comment] 2021-05-30 04:34
Reopened issue to address case-sensitivity

**Comment by khronokernel** [comment] 2021-06-01 17:47
Wanting to verify, could someone try running the below commands and sending the resulting files on the desktop?

```sh
nvram -x 94b73556-2197-4702-82a8-3e1337dafbfb:ApECID > ~/Desktop/lowercase.plist
nvram -x 94B73556-2197-4702-82A8-3E1337DAFBFB:ApECID > ~/Desktop/uppercase.plist
```
Would appreciate it you ran it with both of these args tested:
```sh
nvram 94B73556-2197-4702-82A8-3E1337DAFBFB:gpu-power-prefs=%01%00%00%00
nvram 94b73556-2197-4702-82a8-3e1337dafbfb:gpu-power-prefs=%01%00%00%00
```

Terminal should print the same output regardless of case, so a bit confused why it would have sensitivity for this specifically

**Comment by guanzhangrtk** [comment] 2021-06-02 05:27
@khronokernel here you go:

```
% diff -ru lowercase.plist uppercase.plist 
--- lowercase.plist	2021-06-02 14:13:37.000000000 +0900
+++ uppercase.plist	2021-06-02 14:14:49.000000000 +0900
@@ -2,7 +2,7 @@
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
-	<key>94b73556-2197-4702-82a8-3e1337dafbfb:ApECID</key>
+	<key>94B73556-2197-4702-82A8-3E1337DAFBFB:ApECID</key>
```

The other commands I guess will need to run in single-user mode, which I'm kinda hesitant to do right now. If others cannot do it I'll test it out later, thanks!

**Comment by khronokernel** [comment] 2021-06-17 13:55
OpenCore Legacy Patcher no longer relies on gpu-power-prefs detection so closing

**Closed by khronokernel** 2021-06-17 13:55 UTC
Labels: back-end, bug, help wanted
