### ISSUE TITLE
Opencore-Patcher.command of last Main folder 0.2.0 is not working

### ISSUE THREAD

**Issue by OKonnel** [dortania/OpenCore-Legacy-Patcher#321] opened 2021-06-21 09:14 UTC
I just downloaded the Main release 0.2.0 Code, but starting "Opencore-patcher.command" the EFI Build is not created and in Terminal I get the following.
`Vincenzo@iMac-Studio OpenCore-Legacy-Patcher-main % ./OpenCore-Patcher.command`  
`Traceback (most recent call last):`
`  File "/Users/Vincenzo/Downloads/OpenCore-Legacy-Patcher-main/./OpenCore-Patcher.command", line 10, in <module>`
`    from Resources import (Build, CliMenu, Constants, ModelArray, SysPatch,`
`  File "/Users/Vincenzo/Downloads/OpenCore-Legacy-Patcher-main/Resources/Build.py", line 17, in <module>`
`    from Resources import Constants, ModelArray, Utilities, device_probe`
`  File "/Users/Vincenzo/Downloads/OpenCore-Legacy-Patcher-main/Resources/Constants.py", line 10, in <module>`
`    from Resources import device_probe`
`  File "/Users/Vincenzo/Downloads/OpenCore-Legacy-Patcher-main/Resources/device_probe.py", line 9, in <module>`
`    from Resources import PCIIDArray, Utilities, ioreg`
`  File "/Users/Vincenzo/Downloads/OpenCore-Legacy-Patcher-main/Resources/Utilities.py", line 9, in <module>`
`    import requests`
`ModuleNotFoundError: No module named 'requests'`
Obviously I tried to download the Main Code again, i tried to download every single file in RAW format, but to no avail.
As always, I also deactivated the Quarantine from the entire folder with the command:
`xattr -dr com.apple.quarantine and Path of the folder containing Main release`

**Comment by dhinakg** [comment] 2021-06-21 12:18
duplicate of #317 

Running from source is only intended for developers who can troubleshoot independently, please use the builds if you're not one of them.

**Closed by dhinakg** 2021-06-21 12:18 UTC
