### ISSUE TITLE
Slow crash on eficheck

### ISSUE THREAD

**Issue by volsk** [dortania/OpenCore-Legacy-Patcher#292] opened 2021-06-13 08:58 UTC
My system slowly crashes. UI elements will become unresponsive and every application I click will quit.

While debugging I saw my `/var/log/system.log` is full with lines like below.

What triggerd me is the line
`com.apple.driver.eficheck[2521]): Service exited with abnormal code: 78`.

It seems this slowly hangs my system.

I'm running the latest OLCP on a cMP 4,1>5,1.

````
Jun 13 10:52:26 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck[2435]): Service exited with abnormal code: 78
Jun 13 10:52:26 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jun 13 10:52:27 thor com.apple.xpc.launchd[1] (com.openssh.sshd.5204AD05-EC11-4EB3-A271-ECDE1A223136[2433]): Service exited with abnormal code: 255
Jun 13 10:52:32 thor com.apple.xpc.launchd[1] (com.apple.applefsplaceholder): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jun 13 10:52:35 thor com.apple.xpc.launchd[1] (com.openssh.sshd.6936BA1C-5A95-403D-9820-D47814698800[2461]): Service exited with abnormal code: 255
Jun 13 10:52:35 thor com.apple.xpc.launchd[1] (com.openssh.sshd.9B085EDA-8947-475C-B4F6-80205FFDAF59[2450]): Service exited with abnormal code: 255
Jun 13 10:52:36 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck[2472]): Service could not initialize: 20D91: xpcproxy + 23862 [839][60F99144-8057-38E2-8AC6-AD60B93E6E6B]: 0x1
Jun 13 10:52:36 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck[2472]): Service exited with abnormal code: 78
Jun 13 10:52:36 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jun 13 10:52:42 thor com.apple.xpc.launchd[1] (com.apple.applefsplaceholder): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jun 13 10:52:45 thor com.apple.xpc.launchd[1] (com.openssh.sshd.64D11F16-CEE0-4B03-9612-18F26A4F430F[2474]): Service exited with abnormal code: 255
Jun 13 10:52:46 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck[2477]): Service could not initialize: 20D91: xpcproxy + 23862 [839][60F99144-8057-38E2-8AC6-AD60B93E6E6B]: 0x1
Jun 13 10:52:46 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck[2477]): Service exited with abnormal code: 78
Jun 13 10:52:46 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jun 13 10:52:47 thor sshd: koen [priv][2478]: USER_PROCESS: 2481 ttys002
Jun 13 10:52:52 thor com.apple.xpc.launchd[1] (com.apple.applefsplaceholder): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jun 13 10:52:52 thor com.apple.xpc.launchd[1] (com.openssh.sshd.A749414A-2DD6-4AF7-936E-D98D0E127572[2476]): Service exited with abnormal code: 255
Jun 13 10:52:56 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck[2521]): Service could not initialize: 20D91: xpcproxy + 23862 [839][60F99144-8057-38E2-8AC6-AD60B93E6E6B]: 0x1
Jun 13 10:52:56 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck[2521]): Service exited with abnormal code: 78
Jun 13 10:52:56 thor com.apple.xpc.launchd[1] (com.apple.driver.eficheck): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jun 13 10:52:57 thor com.apple.xpc.launchd[1] (com.openssh.sshd.344A1C5C-8B3A-4243-86BD-2DA6FABFB4A3[2519]): Service exited with abnormal code: 255
````

**Comment by khronokernel** [comment] 2021-06-13 17:17
What OS is this?

**Comment by volsk** [comment] 2021-06-13 17:47
Big Sur 11.2.3.

**Comment by khronokernel** [comment] 2021-06-14 01:14
Could you verify if a clean install can replicate? ie. no previous user data is transferred over

**Comment by volsk** [comment] 2021-06-14 07:50
I might be able to do that today. But I’m afraid it will have to wait a week.

**Comment by jgleigh** [comment] 2021-06-18 13:28
My log on a MacPro5,1 is also full of those eficheck errors, but I'm not getting any performance issues. I'm wondering if the firmware version spoofing is breaking the eficheck.

**Closed** 2021-06-20 19:04 UTC
Labels: waiting-for-response

**Comment by ylluminate** [comment] 2021-06-20 21:59
I too am seeing my `system.log` full of these messages, but no performance issue(s).  I am, however, seeing this:
* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/318

**Comment by jgimeno** [comment] 2021-07-01 11:55
Same here, this happens on a MacPro 5,1 and I get the same behaviour. It slowly crashes every app and even the menu bar dissapears.

**Comment by volsk** [comment] 2021-08-09 05:29
It’s back with the latest build. At some point the system starts crashing. Every app I click crashes and won’t open again. Including Finder and the Menubar.

**Comment by jgimeno** [comment] 2021-08-09 07:50
I had the problem of the menubar also.

**Comment by volsk** [comment] 2021-08-09 08:12
> I had the problem of the menubar also.

What version are you on now? Still 0.2.2? And no problems?

**Comment by dghazfan** [comment] 2021-08-09 17:16
Same problem for me too

**Comment by volsk** [comment] 2021-08-13 10:32
I also started a thread on [StackExchange](https://apple.stackexchange.com/questions/425556/all-apps-crash-on-click-opening). This morning I was toying around again and tried `purge`. After running this command everything came back to live! So, now the question becomes if there is any relation with OCLP and the loaded kexts.

**Comment by Ausdauersportler** [comment] 2021-09-23 12:50
The problem of crashing apps persists and has been discussed on Discord, too. The root cause is still unknown, some believe to be able to reproduce it when using hibernation, others by using non Big Sur generated APFS disks or partitions (e.g. from Mojave).

Some links:

https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-30278902

https://forums.macrumors.com/threads/macos-11-big-sur-on-unsupported-macs-thread.2242172/post-30185084

https://forums.macrumors.com/threads/latebloom-an-experimental-workaround-for-the-11-3-race-condition.2303986/post-30156000

https://apple.stackexchange.com/questions/425556/all-apps-crash-on-click-opening

https://discord.com/channels/417165963327176704/835339735772823573/890419531741294622

and

https://discord.com/channels/417165963327176704/835339735772823573/890338292732678215

It is affecting all my iMacs Late 2009, Mid 2010 and Mid 2011 only using Big Sur later than 11.2.3 (but may be I had it before, because I moved to OCLP back in March after iMac support had been included). 

The iMac12,2 Mid 2011 is not affected by the "race condition" - so there is unlikely a direct link between this problem and the "race condition" unless the upcoming latebloom replacing solution will make a hidden one public.

It may be related in my particular to iCloud (where I synced Desktop and Documents)?

Clean installation or NVRAM reset do not cure the problem. 
After a reboot the problem is gone for a while unless it comes back. 
I cannot force the problem to show up. Sometimes it needs an hour, sometimes days. 
Some users reported it comes back every time they use Big Sur for longer than an hour.
