### ISSUE TITLE
MacBookPro 10,1 : cannot install Big Sur

### ISSUE THREAD

**Issue by Ribero** [dortania/OpenCore-Legacy-Patcher#100] opened 2021-03-14 00:54 UTC
**Describe the bug**
After installing OCLP v0.0.17 to an external USB hard drive and successfully booted on EFI, I was able to start the installation of Big Sur 10.2.2 (also Tried 10.2.1 and 102.3) and select a free partition of the external USB drive for the installation but 12 minutes before the end of installation, the mac reboot and the installation volume is not seen in the volume list and only a new  volume named macOSinstaller appears alongside the Big Sur original installer volume. I tried to boot on this macOSinstaller volumes but it ends up to another reboot and the mac restart on its internal SSD recovery partition (a Mojave one)

**To Reproduce**
1. From my current installation (Mojave 10.14.6) download Big Sur 11.2.1 or 11.2.2 or 11.2.3 and install the package to /Application
2. Format an external USB drive with 2 partition (HFS+/GUID) : 1 for the installer, 1 for where BS will be installed
3. Create a BS install disk to /externalusb/Installer partition
4. launch OCLP 0.0.17, mac correctly detected as MacBookPro10.1, build, then install on EFI partition of the externalusb drive
5. Reboot
6. Select EFI
7. Select InstallmacOSBigSur
8. Start the install
9. Installer takes ages to discover available volumes then ask for unlocking with a known account and display a user of my main interal SSD
10. enter password
11. Start install
12. Select the empty free partition on externalusb (named BBS in my setup)
13. Install start
14. after 15 minutes the installer states the install will finish in 12 minutes but the mac suddenly reboot

**Screenshots**
Console message just before the unexpected reboot:
![IMG_6144 4](https://user-images.githubusercontent.com/2266264/111053954-b0a4fd00-8468-11eb-9a9a-8e31687e5de7.JPG)

Volume list after reboot (sorry for the quality). Please note that the volume BBS does not apears but instead a volume named macOSinstaller (trying to boot on it ends up on the mojave recovery partition) 
![IMG_6145](https://user-images.githubusercontent.com/2266264/111053769-f365d580-8466-11eb-8330-b0a1271e6502.JPG)

**Build Folder**
[Build-Folder.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6135880/Build-Folder.zip)

**Hardware (please complete the following information):**
 - OS Running : macOS 10.14.6 (18G8022)
 - OS Patching macOS 11.2.3, Big Sur (but also trie .1 and .2
 - Model Patching MacBookPro 10,1 (MacBoo Pro Retina 15" mid-2012)

**Additional context**

- I upgraded the WiFi card to AirPort Extreme  (0x14E4, 0x133)/ Broadcom BCM43xx 1.0 (7.77.61.3 AirPortDriverBrcmNIC-1305.11). During macOS BS install I can select a WiFI network and connect to it.
- I previously tried to install BS Beta using https://dortania.github.io/OpenCore-For-Legacy-Macs/ which ends up to remove the battery to get the mac to boot again (Firmware bricking by macOS).
- I successfully ran BS using https://github.com/barrykn/big-sur-micropatcher but this approach does not allow the use of FileVault
- The macbook pro currently run on Mojave 10.14.6 on internal SSD protected by FileVault 2

**Comment by khronokernel** [comment] 2021-03-14 18:50
> and the mac restart on its internal SSD recovery partition (a Mojave one)

Sounds like Big Sur bug regarding SecureBootModel, my recommendation would be to try the following:

* Rebuild OpenCore, however select `Disable SecureBootModel` in Patcher Settings
* Install to USB drive again
* Boot MacBook and reset NVRAM
* Attempt to install macOS Big Sur again

Once you've finished installing, I recommend you re-enable `SecureBootModel` to ensure OS updates function correctly

**Comment by khronokernel** [comment] 2021-03-23 17:13
Closing as assumed resolved

**Comment by Ribero** [comment] 2021-03-23 18:42
@khronokernel Sorry for my late answer.

I tried your suggestion but unfortunately I still was not able to finish the installation and boot on the installed drive.
I had some suspicion about my external USB hdd health so I bought an USB3 Key to do the installation but it finished exactly the same.

I wonder what can cause this issue. Can it be related to the fact I use Filevault on the mojave internal drive ?
Well I need to do complementary tests but each install takes ages... and I use this Macbook for work everyday.

**Comment by khronokernel** [comment] 2021-03-24 14:25
We have another user of similar issue on the Discord server (MacBookPro10,2), however FileVault was not enabled on their machine. From what it seems, NVRAM on your Mac is misbehaving and unfortunately we haven't been able to find a proper work around for these rare cases. We assume it's an underlying hardware issue as we have had plenty of MacBookPro10,x users install perfectly fine.

We'll keep this issue open for tracking, however we're unable to really recommend much in the current state. If new possible solutions arise, we will update this issue thread

**Comment by khronokernel** [comment] 2021-03-24 14:36
@Ribero So I actually have another test for you, we're wondering if it's some NVRAM defragmentation happening. Please try the following:

* [OpenCore-ARD.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6198039/OpenCore-ARD.zip)
* [OpenCore-ARD+PSB.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6198040/OpenCore-ARD%2BPSB.zip)
* [OpenCore-PSB.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6198041/OpenCore-PSB.zip)

**Comment by Ribero** [comment] 2021-03-24 15:09
@khronokernel, thanks a lot for reopening the issue and for your complementary tests proposal.
I will try them asap but more probably this week-end.

**Comment by Ribero** [comment] 2021-03-27 16:10
I'm currently trying ARD. Will take hours. 

Imagine all of the different versions are working :) which one should I use in priority ?

**Comment by khronokernel** [comment] 2021-03-27 16:11
ARD and ARD+PSB are the 2 builds I have some confidence in

**Comment by Ribero** [comment] 2021-03-27 19:36
Just a quick feedback, with ARD, unfortunately I face the same behavior.
I will try the other one tomorrow.

**Comment by Ribero** [comment] 2021-04-03 18:15
Well I tried many things but none of them worked. 
Finally I tried to install Big Sur on my external USB HD and USB Key on an iMac that is normally officially supported. It never worked. The idea was to install it on the usb key then use it on the Macbook Pro. 

I tried many approach on the iMac : install from my mojave install using the official installer -> install stuck after hours

Also tried using creatinstallmedia and boot on it -> same type of issue, install takes forever and if I switch off and restart and boot on BS usb external drive/key it never finish to boot up. 

I do not understand why it is not working with a supported unmodified Mac. There is something wrong in my configuration (network ?) that prevent BS to work even on a supported mac. 

So I won't waste your time trying to solve the install on my unsupported macbook pro if it even do not work on a supported machine. 

I give up and will wait... I don't know what to wait... so disappointed by apple. 

Thanks a lot for your time and patience.

**Comment by khronokernel** [comment] 2021-04-07 00:15
Sorry to hear about this, but as you said if this happens on real Macs there's little OCLP can do to resolve. If you do find that this is actually an OCLP bug in the future, feel free to comment on this thread and we'll reopen

**Closed by khronokernel** 2021-04-07 00:15 UTC
Labels: MacBook Pro, back-end, bug, help wanted

**Comment by Ribero** [comment] 2021-04-27 14:19
Hi @khronokernel,

Sorry to comment a closed issue but I was not sure it was useful to open an issue for theses points:

BigSur install failed on my supported iMac and on my unsupported MacBook Pro 10,1 because it's nearly impossible (often fail) to install BigSur on an external USB drive or USB Key. I found that many users wanting to test Big Sur on supported mac without installing it on internal disk were facing the exact same issue.

So I made a test. On iMac (supported) I added a volume to the internal APFS drive (which host my main File Vault Boot Volume) and launched the install from Mojave : after 30 minutes Big Sur was up & running ! Works like a charm. I rebooted on Mojave and deleted the Data / System / Update volumes added to my drive as I do not want to upgrade this machine yet

Now I made the same with the MacBook Pro 10,1 mid-2012 with an upgrade WiFi:
- Downloaded BS 11.3
- Installed OCLP 1.01 on an external USB Key
- Created the BS installer on the same USB key
- Reboot, select EFI, Boot on BS install from USB Key : I selected the new volume I added to my internal SSD beside my main File Vault Boot Volume, install starts and then get stuck at 12 minutes before the end
- Forced a power off
-  Reboot select MacOS installer : install continue during 40 min
- Finally BS is installed and running smoothly !

Now I did an additional test:
- Shutdown
- Reboot on EFI (from external USB)
- Try to boot my main legacy mojave File Vault Volume -> Fail Complaining about Apple Secure Boot not supported
- Try to boot on the Big Sur freshly installed volume -> works

I also found that after doing a reboot / shutdown macOS Big Sur complains that the computer was not shut-downed safely and probably crashed. The shutdown / reboot does not seems to work as expected (it's very very fast compared to Mojave which takes minutes before closing everything and reboot the mac).

**Comment by khronokernel** [comment] 2021-04-27 14:33
Great to hear it installed, will likely add some documentation regarding this in the troubleshooting section to help users out

> Fail Complaining about Apple Secure Boot not supported -> any idea why ?

This is actually a bug with High Sierra through Catalina regarding secure boot support. Those OSes only supported Secure Boot on T2 machines and so non-T2 models would sometimes have the required signed kernel cache missing. OpenCore has the ability to add Secure Boot support to those older OSes on older hardware for better secuirty than what Apple provided.

With Big Sur, all natively supported Macs have Secure Boot enabled and thus OpenCore does this as well for unsupported Macs. This is actually required for Delta update support, and it's not possible to have selective OSes with Secure Boot support within OpenCore. Currently it's either all OSes or none

> I also found that after doing a reboot / shutdown macOS Big Sur complains that the computer was not shut-downed safely and probably crashed. 

Others are experiencing this as well, seems to be a race condition with the hardware. Currently still being investigated

**Comment by Ribero** [comment] 2021-04-27 14:53
> This is actually a bug with High Sierra through Catalina regarding secure boot support. Those OSes only supported Secure Boot on T2 machines and so non-T2 models would sometimes have the required signed kernel cache missing. OpenCore has the ability to add Secure Boot support to those older OSes on older hardware for better secuirty than what Apple provided.
> 
> With Big Sur, all natively supported Macs have Secure Boot enabled and thus OpenCore does this as well for unsupported Macs. This is actually required for Delta update support, and it's not possible to have selective OSes with Secure Boot support within OpenCore. Currently it's either all OSes or none

Ok so it means there is nothing I can do to boot my Mojave volume. I MUST NOT install UEFI on my internal SSD if I still wan to boot on my Mojave File Vault volume, right ?

**Comment by khronokernel** [comment] 2021-04-27 14:58
> I MUST NOT install UEFI on my internal SSD if I still wan to boot on my Mojave File Vault volume, right ?

Well you can, it's a fairly easy fix for Secure Boot support. This can be done either in Mojave or Recovery's terminal and reboot when done:

```bash
# First, find your Preboot volume
diskutil list

# From the below list, we can see our Preboot volume is disk5s2
/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +255.7 GB   disk5
                                 Physical Store disk4s2
   1:                APFS Volume ⁨Big Sur HD - Data⁩       122.5 GB   disk5s1
   2:                APFS Volume ⁨Preboot⁩                 309.4 MB   disk5s2
   3:                APFS Volume ⁨Recovery⁩                887.8 MB   disk5s3
   4:                APFS Volume ⁨VM⁩                      1.1 MB     disk5s4
   5:                APFS Volume ⁨Big Sur HD⁩              16.2 GB    disk5s5
   6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 16.2 GB    disk5s5s
# Now mount the Preboot volume
diskutil mount disk5s2

# CD into your Preboot volume
# Note the actual volume is under /System/Volumes/Preboot in macOS
# however in Recovery it's simply under /Volumes/Preboot
cd /System/Volumes/Preboot

# Grab your UUID
ls
 46923F6E-968E-46E9-AC6D-9E6141DF52FD
 CD844C38-1A25-48D5-9388-5D62AA46CFB8

# If multiple show up(ie. you dual boot multiple versions of macOS), you will
# need to determine which UUID is correct.
# Easiest way to determine is printing the value of .disk_label.contentDetails
# of each volume.
cat ./46923F6E-968E-46E9-AC6D-9E6141DF52FD/System/Library/CoreServices/.disk_label.contentDetails
 Big Sur HD%

cat ./CD844C38-1A25-48D5-9388-5D62AA46CFB8/System/Library/CoreServices/.disk_label.contentDetails
 Catalina HD%

# Next lets copy over the secure boot files, recovery will need different commands

# Example commands for inside macOS
# Replace CD844C38-1A25-48D5-9388-5D62AA46CFB8 with your UUID value
cd ~
sudo cp -a /usr/standalone/i386/. /System/Volumes/Preboot/CD844C38-1A25-48D5-9388-5D62AA46CFB8/System/Library/CoreServices

# Example commands for Recovery
# Replace Macintosh\ HD and CD844C38-1A25-48D5-9388-5D62AA46CFB8 with
# your System Volume's name and Preboot's UUID
cp -a /Volumes/Macintosh\ HD/usr/standalone/i386/. /Volumes/Preboot/CD844C38-1A25-48D5-9388-5D62AA46CFB8/System/Library/CoreServices
```

**Comment by Ribero** [comment] 2021-04-27 15:00
Nice, I will try, thanks !

**Comment by Ribero** [comment] 2021-04-27 15:00
> > I also found that after doing a reboot / shutdown macOS Big Sur complains that the computer was not shut-downed safely and probably crashed.
> 
> Others are experiencing this as well, seems to be a race condition with the hardware. Currently still being investigated

Do you want me to open/comment a new/existing issue on this point ?

**Comment by khronokernel** [comment] 2021-04-27 15:01
Nah for now no, as this seems to be a macOS issue and not OCLP

**Comment by Ribero** [comment] 2021-04-28 07:13
> 
> Next lets copy over the secure boot files, recovery will need different commands
> 
> Example commands for inside macOS
> Replace CD844C38-1A25-48D5-9388-5D62AA46CFB8 with your UUID value
> cd ~
> sudo cp -a /usr/standalone/i386/. /System/Volumes/Preboot/CD844C38-1A25-48D5-9388-5D62AA46CFB8/System/Library/CoreServices
> 
> Example commands for Recovery
> Replace Macintosh\ HD and CD844C38-1A25-48D5-9388-5D62AA46CFB8 with
> your System Volume's name and Preboot's UUID
> cp -a /Volumes/Macintosh\ HD/usr/standalone/i386/. /Volumes/Preboot/CD844C38-1A25-48D5-9388-5D62AA46CFB8/System/Library/CoreServices

- I booted on Mojave
- I mounted Preboot Partition (in `/Volume/Preboot` rather than `/Volume/Systems/Preboot`)
- I found the UUID of the Mojave File Vault boot volume

Then I do not understand the 2 last cp commands. I want to be sure before doing any irreversible things.
If I understand that the cp commands are going to overwrite the `/Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices` with files in` /usr/standalone/i386/.` from my Mojave Boot Volume, right ?

```
ls -lFa /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices
total 1408
drwxr-xr-x  33 root  wheel    1056 27 avr 12:27 ./
drwxr-xr-x   4 root  wheel     128  4 nov  2019 ../
-rw-r--r--@  1 root  wheel     281 27 avr 12:27 .disk_label
-rw-r--r--@  1 root  wheel       4 27 avr 12:27 .disk_label.contentDetails
-rw-r--r--@  1 root  wheel    1133 27 avr 12:27 .disk_label_2x
-rw-r--r--@  1 root  wheel      36 27 avr 12:15 .root_uuid
-rw-r--r--   1 root  wheel      32 27 avr 10:08 BridgeVersion.bin
-rw-r--r--   1 root  wheel     523 27 avr 10:08 BridgeVersion.plist
-rw-r--r--   1 root  wheel    4580 23 jan  2020 PlatformSupport.plist
-r--r--r--   1 root  wheel     535 14 avr 08:17 SystemVersion.plist
-rw-r--r--   1 root  wheel  592440 29 jan  2020 boot.efi
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.j132ap.im4m
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.j137ap.im4m
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.j140aap.im4m
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.j140kap.im4m
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.j174ap.im4m
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.j213ap.im4m
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.j680ap.im4m
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.j780ap.im4m
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.x589amludev.im4m
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.x589icludev.im4m
-rw-r--r--   1 root  wheel    2738 14 avr 11:07 boot.efi.x589iclydev.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.j132ap.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.j137ap.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.j140aap.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.j140kap.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.j174ap.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.j213ap.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.j680ap.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.j780ap.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.x589amludev.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.x589icludev.im4m
-rw-r--r--   1 root  wheel    2738 21 sep  2019 bootbase.efi.x589iclydev.im4m
```

```
ls -lFa /usr/standalone/i386/.
total 33160
drwxr-xr-x  18 root  wheel       576 27 avr 10:07 ./
drwxr-xr-x   5 root  wheel       160 21 sep  2019 ../
drwxr-xr-x  14 root  wheel       448 28 jui  2019 EfiLoginUI/
-rw-r--r--   1 root  wheel  15729264 23 fév  2019 Firmware.scap
drwxr-xr-x   3 root  wheel        96 23 fév  2019 SecureBoot.bundle/
-rw-r--r--   1 root  wheel    602968  9 mar 09:41 apfs.efi
-rw-r--r--   1 root  wheel    592440  3 déc  2019 boot.efi
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.j132ap.im4m
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.j137ap.im4m
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.j140aap.im4m
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.j140kap.im4m
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.j174ap.im4m
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.j213ap.im4m
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.j680ap.im4m
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.j780ap.im4m
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.x589amludev.im4m
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.x589icludev.im4m
-rw-r--r--   1 root  wheel      3149 14 avr 11:08 boot.efi.x589iclydev.im4m
```

And then do the same thing for the recovery partition.

**Comment by Ausdauersportler** [comment] 2021-04-28 11:47
I can confirm the same problem (we talked in private about this before). Only with SecureBootModel disabled one can boot into Mojave or High Sierra (which runs great with OCLP).

Same question: What is the intended source of the copy command and what is the intended target?

1. In fact running macOS Mojave (not the recovery) the Mojave Preboot partition mounts to `/Volumes/Preboot` using the `sudo diskutil mount diskXs2` command.
2. Running Big Sur the same command `sudo diskutil mount diskXs2` mounts the Big Sur Preboot volume to `/dev/disk2s2 on /System/Volumes/Preboot (apfs, local, journaled, nobrowse)` - which reflects your guide above perfectly.

Do we have to replace the contents of the Mojave Preboot partition with the files found in `/usr/standalone/i386/.` from the Mojave installation? 

Would like to check this out - this is a test machine. No data will be lost, only life time to install :-)

**Comment by Ausdauersportler** [comment] 2021-04-29 16:33
To make this clear:

One has just to copy the (High Sierra or) Mojave files from (the source) the local `/usr/standalone/i386` over to the (the target) `PreBoot` and `Recovery` partitions using the correct UUID as described above.

**Comment by Ribero** [comment] 2021-04-29 16:56
```
sudo cp -a /usr/standalone/i386/. /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/
Password:
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.j213ap.im4m: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./Firmware.scap: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.j780ap.im4m: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.j680ap.im4m: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI: Operation not permitted
cp: /usr/standalone/i386/./EfiLoginUI: unable to copy extended attributes to /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/appleLogo.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/flag_picker.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/unknown_userUI.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/sound.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/battery.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/recoveryUI.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/Lucida13.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/disk_passwordUI.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/recovery_user.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/Lucida13White.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/loginui.efires: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI/guest_userUI.efires: No such file or directory
cp: utimes: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI: No such file or directory
cp: chown: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI: No such file or directory
cp: chmod: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI: No such file or directory
cp: chflags: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI: No such file or directory
cp: /usr/standalone/i386/./EfiLoginUI: unable to copy ACL to /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./EfiLoginUI: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./apfs.efi: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.x589amludev.im4m: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.j132ap.im4m: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.x589iclydev.im4m: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle: Operation not permitted
cp: /usr/standalone/i386/./SecureBoot.bundle: unable to copy extended attributes to /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents: No such file or directory
cp: /usr/standalone/i386/./SecureBoot.bundle/Contents: unable to copy extended attributes to /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature: No such file or directory
cp: /usr/standalone/i386/./SecureBoot.bundle/Contents/_CodeSignature: unable to copy extended attributes to /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature/CodeResources: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature/CodeDirectory: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature/CodeSignature: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature/CodeRequirements: No such file or directory
cp: utimes: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature: No such file or directory
cp: chown: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature: No such file or directory
cp: chmod: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature: No such file or directory
cp: chflags: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature: No such file or directory
cp: /usr/standalone/i386/./SecureBoot.bundle/Contents/_CodeSignature: unable to copy ACL to /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/_CodeSignature: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/Resources: No such file or directory
cp: /usr/standalone/i386/./SecureBoot.bundle/Contents/Resources: unable to copy extended attributes to /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/Resources: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/Resources/BuildManifest.plist: No such file or directory
cp: utimes: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/Resources: No such file or directory
cp: chown: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/Resources: No such file or directory
cp: chmod: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/Resources: No such file or directory
cp: chflags: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/Resources: No such file or directory
cp: /usr/standalone/i386/./SecureBoot.bundle/Contents/Resources: unable to copy ACL to /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/Resources: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/Info.plist: No such file or directory
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents/version.plist: No such file or directory
cp: utimes: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents: No such file or directory
cp: chown: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents: No such file or directory
cp: chmod: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents: No such file or directory
cp: chflags: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents: No such file or directory
cp: /usr/standalone/i386/./SecureBoot.bundle/Contents: unable to copy ACL to /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle/Contents: No such file or directory
cp: utimes: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle: No such file or directory
cp: chown: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle: No such file or directory
cp: chmod: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle: No such file or directory
cp: chflags: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle: No such file or directory
cp: /usr/standalone/i386/./SecureBoot.bundle: unable to copy ACL to /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./SecureBoot.bundle: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.j137ap.im4m: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.x589icludev.im4m: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.j140aap.im4m: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.j140kap.im4m: Operation not permitted
cp: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/./boot.efi.j174ap.im4m: Operation not permitted
cp: utimes: /Volumes/Preboot/FA0F0CB7-D785-4D75-B530-07C1723487CD/System/Library/CoreServices/.: Operation not permitted

```

**Comment by Ausdauersportler** [comment] 2021-04-29 21:38
Come on, the old story: 

1. disable SIP in OCLP: `csr-active-config  FF0F0000 DATA`
2. reboot
3. mount the Preboot volume and re-mount read/write using `sudo mount -uw /Volumes/Preboot`
