### ISSUE TITLE
Stuck in loop at Login screen!

### ISSUE THREAD

**Issue by sharad-paghadal** [dortania/OpenCore-Legacy-Patcher#246] opened 2021-05-25 16:17 UTC
Everything is working fine before I apply Post Install Volume Patches.

**To Reproduce**
1. Upon applying volume patch for graphics, after reboot, it looped me in login screen.
2. I enter correct password, and it still asking me the same again and again.
3. Please note that entering wrong password animate the password field, but in my case it’s accepting the password and again move me back to login screen

**Hardware:**
 - OS Running MacOS 11.3.1
 - Macmini5,2

**Comment by dhinakg** [comment] 2021-05-25 16:21
Duplicate of #245, see #108

**Closed by dhinakg** 2021-05-25 16:21 UTC

**Comment by sharad-paghadal** [comment] 2021-05-25 16:25
@dhinakg any workaround or quick fix for now?
