### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by jefftr66** [dortania/Opencore-Legacy-Patcher#16] opened 2020-12-09 00:25 UTC
![Screen Shot 2020-12-08 at 16 23 06](https://user-images.githubusercontent.com/46849235/101557412-d0acb800-3971-11eb-82c6-6e60a2cee962.png)
I keep getting OpenCore-Legacy-Patcher is damaged error and it makes me trash the program. Any thoughts?

**Comment by porcherie** [comment] 2020-12-09 08:12
If you install Xcode command tools and then allow terminal in system preference->dev tools it works

**Comment by jefftr66** [comment] 2020-12-09 17:23
Thanks - I had Xcode installed but the Sys Pref wasn't selected. I will give it a try.

**Comment by khronokernel** [comment] 2020-12-12 19:42
Duplicate of https://github.com/dortania/Opencore-Legacy-Patcher/issues/8

**Closed by khronokernel** 2020-12-12 19:42 UTC
