### ISSUE TITLE
[Bug]: 0.25 don´t support 2 monitor with cMP5.1 an 5700xt

### ISSUE THREAD

**Issue by CyberMODE** [dortania/OpenCore-Legacy-Patcher#466] opened 2021-08-30 08:11 UTC
### Machine Model

MacPro5,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Within macOS (Before Logging in)

### What is the Isssue?

With OC LP 0.24 2 monitors work perfect with BS, but when i apple the nightly build, only a monitor work.

I have a MacPro 5.1 with a Radeon RX 5700 XT

TIA

**Comment by khronokernel** [comment] 2021-08-30 22:23
Technically a duplicate of this issue:

* https://github.com/dortania/OpenCore-Legacy-Patcher/issues/451

We plan to have it fixed before 0.2.5 releases, a temporary fix is to patch this function:

* https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/Resources/Build.py#L536-L571

Basically you need to report that the `if device.pci_path:` is not present. Changing it to `if false:` will allow the boot-args to be installed. If you're unsure of how to manually edit and run OCLP, I would recommend waiting for that issue to be resolved

**Closed by khronokernel** 2021-08-30 22:23 UTC
Labels: bug
