### ISSUE TITLE
MBP9,2 apple try update SMC

### ISSUE THREAD

**Issue by CuchoM** [dortania/OpenCore-Legacy-Patcher#104] opened 2021-03-15 22:01 UTC
**Describe the bug**
Upgrading to BS11.3 any beta version apple tried to upgrade smc on MBP9,2 writing again apple directory at EFI, OC obviously blocked the installation , and finished updade to BS11.3 b4 20E5210c
 

**Additional context**
Is there any way to show a high number at SMC version  :
current
System firmware version:	9999.999.999.999.999
 SMC Version    (system):	2.2f44

**Comment by khronokernel** [comment] 2021-03-15 22:08
Oh thanks for bringing this to light, there actually is a property for this called `SmcVersion` under PlatformInfo -> SMBIOS.

I'd need to take a peak at the SMCUpdater.efi to see what format it expects and can integrate that into the patcher, I will likely need to add a property within OpenCore for users relying on Moderate or higher SMBIOS patching as well.

**Comment by khronokernel** [comment] 2021-03-15 22:21
Checked the format, this will result in the SMC being set to `9.999999`(it's just a simple ASCII to Hex conversion, however the ASCII chars are hex as well):

```
PlatformInfo:
   SMBIOS:
      SmcVersion | Data | 392e393939393939
```

To mount the EFI where OpenCore is stored, use [MountEFI](https://github.com/corpnewt/MountEFI). Do ensure that you didn't build your OpenCore config with Vault enabled, as that will result in a security violation if you try to edit. If you did, simply rebuild OpenCore in the patcher with Patcher Settings set accordingly.

Will test locally if this correctly updates the var. I will however need to reverse the SMC Updater hopefully later today to ensure `SmcVersion` is the var it pulls to determine whether SMC update is required

**Comment by khronokernel** [comment] 2021-03-15 23:37
After tracking through a few binaries, I've found that :

1. `SMCFlasher` is called by`/usr/libexec/smcupdater`
2. `/usr/libexec/smcupdater` determines SMC version via the `sms-version` property in IOReg. 
3. `sms-version` is original generated by AppleSMC.kext however the issue is where it pulls. It pulls from the hardware itself and *not* from SMBIOS which makes this a lot more complicated.

To work around this, we have 3 options:

* Attempt to overwrite `smc-version`'s value after it's set
  * Would need to look into [VirtualSMC](https://github.com/acidanthera/VirtualSMC)'s implementation
* Patch out `/usr/libexec/smcupdater`'s `smc-version` check
  * This is a headache as we need to reverse more and figure out how to work around it.
* Fix `BlacklistAppleUpdate` to ensure it's *never* booted or even displayed in OpenCore's picker

The last option is actually already implemented, however broke in 11.3 for some odd reason. It actually attempts updates on my hackintosh as well however never got around to debugging it as I hadn't heard any other reports. However if it runs SMCFlasher then we likely need to add a specific check for it

**Comment by MikeBeaton** [comment] 2021-03-16 07:05
Just wondering if someone could help by mentioning which hardware specs I should be looking at, to decide whether the SMC update might be valid for my machine? E.g. I have a MacBookPro10,2 and if it is spoofed to a MacBookPro11,1, then maybe the relevant hardware is actually the same, and the SMC update would be fine.

Also - I guess this must be wrong somehow, but I have to ask: if the SMC updater is looking at the actual hardware to decide whether it needs updating, then isn't this update likely to be *correct*?

I mean, the user may still want to block it, but if it works this way, it would be correct for the actual machine, not correct for the spoofed machine. So much safer. (Or not?!)

**Comment by MikeBeaton** [comment] 2021-03-16 12:33
@khronokernel - not sure if you'll pick this up, but see point above; also, not sure to what extent my config is a supported one, but I often boot Big Sur both inside and outside OpenCore.

Assuming there are a few other users like me, then fixes which only work as long as one is always inside OpenCore are not as valuable.

E.g. the MaxBIOSVersion fix was fine, because it prevents the EFI update being prepared. So even if you then boot outside OpenCore, the update will not happen, as it never gets set up to happen.

**Comment by khronokernel** [comment] 2021-03-16 13:13
> then isn't this update likely to be correct?

The issue is the convoluted way Apple does this, I should elaborate a bit more on how Apple does the probe:

* AppleSMC.kext probes a specific SMC key(`RVBF` iirc) and sets the `sms-version` property based off the value
* smcupdater first probes board ID, *then* probes `smc-version`. It doesn't do any extra checks on hardware variations

This means that SMC payloads for other machines would be applied causing issues. Thankfully OpenCore's Secure Boot prevents random updaters to be launched which avoids SMCFlasher.efi from starting and bricking the SMC.

Me and Vit were discussing this last night, a simple plist only injector and patching out AppleSMC's `smc-version` should do the trick. I plan to mess with it more this evening (for reference, 7am rn for me ;p)

**Comment by khronokernel** [comment] 2021-03-16 13:39
Got the patch to work sucessfully:

```
Identifier | com.apple.driver.AppleSMC
Find       | 736D632D76657273696F6E
Replace    | 6F6C642D76657273696F6E
```
Just a simple `smc` -> `old` replacement. Will finish the plist-only kext later today and add to the patcher

**Comment by MikeBeaton** [comment] 2021-03-16 13:40
Thanks - that's great.

This prevents the update from being scheduled, rather than preventing it at boot once it is scheduled, is that right? Ty.

**Comment by khronokernel** [comment] 2021-03-16 13:42
> This prevents the update from being scheduled, rather than preventing it at boot once it is scheduled, is that right? Ty.

Correct, so `smcupdater` will always see an updated SMC version and assume no reason to update the firmware

**Comment by khronokernel** [comment] 2021-03-16 14:47
Apparently I'm good at procrastinating real work so SMC-Spoof.kext + AppleSMC Patch are in main now. Note that on 10.6, System Report actually pulls from the SMC Key directly however newer OSes correctly pull from AppleSMC's IOReg entry

**Comment by CuchoM** [comment] 2021-03-17 09:48
I've tested in my MBP9,2 and didn't work: Apple still tried to update my SMC, this was blocked by Opencore, everything is working fine, just boot time increased a little.
<img width="1440" alt="Captura de ecrã 2021-03-17, às 08 19 32" src="https://user-images.githubusercontent.com/72659668/111447737-a0f61480-8705-11eb-9b4a-b2a9d985b1c7.png">

**Comment by khronokernel** [comment] 2021-03-17 13:55
@CuchoM Hrrmm, that's unfortunate. Only thing I would recommend is to test deleting `EFI/APPLE` from the EFI and try again. Otherwise it's something we'll need to mess with in OpenCore

**Comment by khronokernel** [comment] 2021-03-17 13:58
Actually I do have 1 last lest, in your config.plist head to `Kernel -> Patch` and find the `Patch SMC` section. Change `Count` to `0`

**Comment by CuchoM** [comment] 2021-03-17 17:34
I've tried and still the same
![Captura de ecrã 2021-03-17, às 14 44 13](https://user-images.githubusercontent.com/72659668/111511449-a889dd80-8746-11eb-8232-3fc71184c448.png)
![Captura de ecrã 2021-03-17, às 14 45 16](https://user-images.githubusercontent.com/72659668/111511470-ade72800-8746-11eb-9940-3eda2d988735.png)
![Captura de ecrã 2021-03-17, às 14 46 33](https://user-images.githubusercontent.com/72659668/111511488-b3dd0900-8746-11eb-89ed-0ca515aa617e.png)
![Captura de ecrã 2021-03-17, às 17 28 58](https://user-images.githubusercontent.com/72659668/111511497-b7709000-8746-11eb-8a49-5827f8105227.png)
[config.plist.zip](https://github.com/dortania/OpenCore-Legacy-Patcher/files/6158382/config.plist.zip)

**Comment by khronokernel** [comment] 2021-03-19 00:34
@CuchoM So I did more testing and still cannot trigger the install, I'm wondering if you're getting confused about how firmware updates. How do you exactly notice these updates start? Is OpenCore actually booting MultiUpdater/SMCflasher.efi or are you watching the print logs inside the installation? Or are you simply assuming the firmware update starts because the payloads are in your EFI?

Just want to make sure there's no miscommunication

**Comment by CuchoM** [comment] 2021-03-19 09:14
Now I am simply assuming the firmware update starts because the payloads are in my EFI. In older versions of BS it didn't happen, I am also using the lasted OC available.

**Comment by khronokernel** [comment] 2021-03-19 14:45
Oh then there is no issue, as the firmware updates cannot start regardless with BlacklistAppleUpdate. I thought you were referring to the update actually starting as you referenced [here](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/104#issuecomment-800945853). For reference, even on my MacBook7,1 I have the firmware update payloads on the EFI but they never start so there is no reason for concern.

Closing as there's no actual harm

**Closed by khronokernel** 2021-03-19 14:45 UTC
Labels: back-end, bug
